/* ════════════════════════════════════════
   SubnetMaster – Language Translations v1.1
   FIX: setLang now updates html lang attribute + dir
   ════════════════════════════════════════ */

const LANGS = {
  de: {
    dir:'ltr',
    nav:{ trainer:'Trainer', lernen:'Lexikon', anleitung:'Anleitung' },
    eyebrow:'Subnetting Trainer',
    title:'Subnetze rechnen', span:'ohne Fehler.',
    sub:'Übe Subnetting mit zufällig generierten Aufgaben. Bei jedem Fehler siehst du eine Schritt-für-Schritt Erklärung.',
    ctaText:'Aufgabe starten',
    slDone:'Aufgaben gelöst', slCorrect:'Richtige Antworten', slPct:'Trefferquote', slStreak:'Aktuelle Serie',
    lblTask:'Aktuelle Aufgabe', lblNetwork:'Netzwerk', lblNeeded:'Benötigt',
    lblQuestions:'Fragen beantworten',
    btnNew:'Neue Aufgabe', btnCheck:'Antworten prüfen',
    maskLabel:'Subnetzmaske', hostsLabel:'Verfügbare Hosts',
    srLabel:(sr,pc) => `${sr} Schulungsräume (je ${pc} PCs)`,
    vwLabel:(vw)    => `1 Verwaltungsnetz (${vw} PCs)`,
    rsLabel:(rs)    => `1 Reservenetz (${rs} PCs)`,
    solHeader:'Alle richtigen Antworten',
    scorePerfect:(t)   => `🎉 Perfekt! Alle ${t}/${t} richtig!`,
    scoreGood:(c,t)    => `👍 Gut! ${c}/${t} richtig — schau dir die Erklärungen an.`,
    scoreRetry:(c,t)   => `💪 ${c}/${t} richtig — lies die Erklärungen und versuch es nochmal!`,
    badgeOk:'✓ Richtig', badgeErr:'✗ Falsch',
    explainTitle:(ans) => `Richtige Antwort: ${ans} — so geht es:`,
    qTexts:[
      'Zu welcher Klasse gehört die IP-Adresse?',
      'Anzahl der benötigten Subnetze (als 2er-Potenz)',
      'Anzahl der entliehenen Subnetzbits (4. Byte)',
      'Anzahl der erforderlichen Hostadressen',
      'Erforderliche Anzahl der Hostbits',
      'Passende Präfixlänge (/-Notation)',
      'Subnetzmaske',
      'Gesamtzahl der Adressen je Subnetz',
      'Tatsächlich verwendbare Hostadressen pro Subnetz',
      'Wie viele Netze sind theoretisch möglich?'
    ],
    qPh:['z.B. C','z.B. 16','z.B. 4','z.B. 12','z.B. 4','z.B. /28','z.B. 255.255.255.240','z.B. 16','z.B. 14','z.B. 16'],
    solKeys:['Klasse','Subnetze','Subnetzbits','Erf. Hosts','Hostbits','Präfix','Subnetzmaske','Adressen/Subnetz','Nutzb. Hosts','Theor. Netze'],
    how:[
      {num:'01', title:'Aufgabe lesen',     text:'Lies das Netz und die benötigten Subnetze.'},
      {num:'02', title:'Antworten eingeben',text:'Füll alle 10 Felder aus. Enter springt zur nächsten Frage.'},
      {num:'03', title:'Prüfen & lernen',   text:'Bei einem Fehler erscheint eine Schritt-für-Schritt Erklärung.'},
      {num:'04', title:'Serie aufbauen',    text:'Lös Aufgaben fehlerfrei und bau deine Serie aus.'}
    ],
    footerText:'SubnetMaster — Klasse 1aAPC',
  },
  en: {
    dir:'ltr',
    nav:{ trainer:'Trainer', lernen:'Reference', anleitung:'Guide' },
    eyebrow:'Subnetting Trainer',
    title:'Calculate subnets', span:'without mistakes.',
    sub:'Practice subnetting with randomly generated tasks. Every mistake shows you a step-by-step explanation.',
    ctaText:'Start exercise',
    slDone:'Tasks solved', slCorrect:'Correct answers', slPct:'Accuracy', slStreak:'Current streak',
    lblTask:'Current task', lblNetwork:'Network', lblNeeded:'Required',
    lblQuestions:'Answer the questions',
    btnNew:'New task', btnCheck:'Check answers',
    maskLabel:'Subnet mask', hostsLabel:'Available hosts',
    srLabel:(sr,pc) => `${sr} training rooms (${pc} PCs each)`,
    vwLabel:(vw)    => `1 admin network (${vw} PCs)`,
    rsLabel:(rs)    => `1 reserve network (${rs} PCs)`,
    solHeader:'All correct answers',
    scorePerfect:(t)   => `🎉 Perfect! All ${t}/${t} correct!`,
    scoreGood:(c,t)    => `👍 Good! ${c}/${t} correct — check the explanations.`,
    scoreRetry:(c,t)   => `💪 ${c}/${t} correct — read the explanations and try again!`,
    badgeOk:'✓ Correct', badgeErr:'✗ Wrong',
    explainTitle:(ans) => `Correct answer: ${ans} — here's how:`,
    qTexts:[
      'Which class does the IP address belong to?',
      'Number of required subnets (power of 2)',
      'Borrowed subnet bits (4th byte)',
      'Number of required host addresses',
      'Required number of host bits',
      'Correct prefix length (slash notation)',
      'Subnet mask',
      'Total addresses per subnet',
      'Usable host addresses per subnet',
      'How many networks are theoretically possible?'
    ],
    qPh:['e.g. C','e.g. 16','e.g. 4','e.g. 12','e.g. 4','e.g. /28','e.g. 255.255.255.240','e.g. 16','e.g. 14','e.g. 16'],
    solKeys:['Class','Subnets','Subnet bits','Req. hosts','Host bits','Prefix','Subnet mask','Addr/subnet','Usable hosts','Theor. nets'],
    how:[
      {num:'01', title:'Read the task',    text:'Look at the network and the required subnets above.'},
      {num:'02', title:'Enter answers',    text:'Fill in all 10 fields. Press Enter to jump to next.'},
      {num:'03', title:'Check & learn',    text:'A wrong answer shows a step-by-step explanation.'},
      {num:'04', title:'Build a streak',   text:'Solve tasks perfectly and grow your streak counter.'}
    ],
    footerText:'SubnetMaster — Class 1aAPC',
  },
  ar: {
    dir:'rtl',
    nav:{ trainer:'المدرب', lernen:'القاموس', anleitung:'الدليل' },
    eyebrow:'مدرب تقسيم الشبكات',
    title:'احسب الشبكات الفرعية', span:'بدون أخطاء.',
    sub:'تدرب على تقسيم الشبكات مع تمارين عشوائية. عند كل خطأ ستظهر لك شرح خطوة بخطوة.',
    ctaText:'ابدأ التمرين',
    slDone:'تمارين محلولة', slCorrect:'إجابات صحيحة', slPct:'نسبة الدقة', slStreak:'السلسلة الحالية',
    lblTask:'التمرين الحالي', lblNetwork:'الشبكة', lblNeeded:'المطلوب',
    lblQuestions:'أجب على الأسئلة',
    btnNew:'تمرين جديد', btnCheck:'تحقق من الإجابات',
    maskLabel:'قناع الشبكة', hostsLabel:'المضيفون المتاحون',
    srLabel:(sr,pc) => `${sr} غرفة تدريب (${pc} جهاز لكل غرفة)`,
    vwLabel:(vw)    => `1 شبكة إدارة (${vw} أجهزة)`,
    rsLabel:(rs)    => `1 شبكة احتياطية (${rs} أجهزة)`,
    solHeader:'جميع الإجابات الصحيحة',
    scorePerfect:(t)   => `🎉 ممتاز! جميع ${t}/${t} صحيحة! مبروك!`,
    scoreGood:(c,t)    => `👍 أحسنت! ${c}/${t} صحيحة — راجع الشرح.`,
    scoreRetry:(c,t)   => `💪 ${c}/${t} صحيحة — اقرأ الشرح وحاول مرة أخرى!`,
    badgeOk:'✓ صحيح', badgeErr:'✗ خطأ',
    explainTitle:(ans) => `الإجابة الصحيحة: ${ans} — إليك الطريقة:`,
    qTexts:[
      'إلى أي فئة تنتمي عنوان IP؟',
      'عدد الشبكات الفرعية المطلوبة (قوة للعدد 2)',
      'عدد البتات المستعارة (البايت الرابع)',
      'عدد عناوين المضيفين المطلوبة',
      'عدد بتات المضيف المطلوبة',
      'طول البادئة المناسب (صيغة الشرطة)',
      'قناع الشبكة الفرعية',
      'إجمالي عدد العناوين لكل شبكة فرعية',
      'عناوين المضيفين القابلة للاستخدام لكل شبكة',
      'كم شبكة فرعية ممكنة نظرياً؟'
    ],
    qPh:['مثال: C','مثال: 16','مثال: 4','مثال: 12','مثال: 4','مثال: /28','مثال: 255.255.255.240','مثال: 16','مثال: 14','مثال: 16'],
    solKeys:['الفئة','الشبكات','بتات الشبكة','المضيفون المطلوبون','بتات المضيف','البادئة','قناع الشبكة','عناوين/شبكة','مضيفون صالحون','شبكات نظرية'],
    how:[
      {num:'٠١', title:'اقرأ التمرين',  text:'انظر إلى الشبكة والشبكات الفرعية المطلوبة.'},
      {num:'٠٢', title:'أدخل الإجابات',text:'أكمل الحقول العشرة. Enter للانتقال للتالي.'},
      {num:'٠٣', title:'تحقق وتعلم',   text:'عند الخطأ يظهر شرح خطوة بخطوة.'},
      {num:'٠٤', title:'ابنِ سلسلتك',  text:'حل التمارين بشكل صحيح وازدد سلسلتك.'}
    ],
    footerText:'SubnetMaster — الصف 1aAPC',
  },
  tr: {
    dir:'ltr',
    nav:{ trainer:'Antrenör', lernen:'Sözlük', anleitung:'Kılavuz' },
    eyebrow:'Alt Ağ Eğitmeni',
    title:'Alt ağları hesapla', span:'hatasız.',
    sub:'Rastgele görevlerle alt ağ hesaplamasını pratik yap. Her hatada adım adım açıklama görürsün.',
    ctaText:'Göreve başla',
    slDone:'Çözülen görevler', slCorrect:'Doğru cevaplar', slPct:'İsabet oranı', slStreak:'Mevcut seri',
    lblTask:'Mevcut görev', lblNetwork:'Ağ', lblNeeded:'Gerekli',
    lblQuestions:'Soruları cevapla',
    btnNew:'Yeni görev', btnCheck:'Cevapları kontrol et',
    maskLabel:'Alt ağ maskesi', hostsLabel:'Kullanılabilir hostlar',
    srLabel:(sr,pc) => `${sr} eğitim odası (her biri ${pc} PC)`,
    vwLabel:(vw)    => `1 yönetim ağı (${vw} PC)`,
    rsLabel:(rs)    => `1 yedek ağ (${rs} PC)`,
    solHeader:'Tüm doğru cevaplar',
    scorePerfect:(t)   => `🎉 Mükemmel! ${t}/${t} doğru!`,
    scoreGood:(c,t)    => `👍 Güzel! ${c}/${t} doğru — açıklamalara bak.`,
    scoreRetry:(c,t)   => `💪 ${c}/${t} doğru — açıklamaları oku ve tekrar dene!`,
    badgeOk:'✓ Doğru', badgeErr:'✗ Yanlış',
    explainTitle:(ans) => `Doğru cevap: ${ans} — adımlar:`,
    qTexts:[
      'IP adresi hangi sınıfa ait?',
      'Gerekli alt ağ sayısı (2\'nin kuvveti)',
      'Ödünç alınan bit sayısı (4. bayt)',
      'Gerekli host adresi sayısı',
      'Gerekli host bit sayısı',
      'Önek uzunluğu (/ notasyonu)',
      'Alt ağ maskesi',
      'Alt ağ başına toplam adres',
      'Kullanılabilir host adresleri',
      'Teorik ağ sayısı'
    ],
    qPh:['örn. C','örn. 16','örn. 4','örn. 12','örn. 4','örn. /28','örn. 255.255.255.240','örn. 16','örn. 14','örn. 16'],
    solKeys:['Sınıf','Alt ağlar','Subnet bitleri','Ger. hostlar','Host bitleri','Önek','Alt ağ maskesi','Adres/ağ','Kullan. hostlar','Teor. ağlar'],
    how:[
      {num:'01', title:'Görevi oku',       text:'Ağı ve gereken alt ağları incele.'},
      {num:'02', title:'Cevapları gir',    text:'10 alanı doldur. Enter ile sonrakine geç.'},
      {num:'03', title:'Kontrol et & öğren',text:'Yanlış cevapta açıklama çıkar.'},
      {num:'04', title:'Seri oluştur',     text:'Görevleri hatasız çöz.'}
    ],
    footerText:'SubnetMaster — Sınıf 1aAPC',
  },
  fr: {
    dir:'ltr',
    nav:{ trainer:'Entraîneur', lernen:'Référence', anleitung:'Guide' },
    eyebrow:'Entraîneur Subnetting',
    title:'Calculer les sous-réseaux', span:'sans erreur.',
    sub:'Entraîne-toi avec des exercices aléatoires. Chaque erreur affiche une explication étape par étape.',
    ctaText:'Commencer',
    slDone:'Exercices résolus', slCorrect:'Réponses correctes', slPct:'Précision', slStreak:'Série',
    lblTask:'Exercice actuel', lblNetwork:'Réseau', lblNeeded:'Requis',
    lblQuestions:'Répondre aux questions',
    btnNew:'Nouvel exercice', btnCheck:'Vérifier',
    maskLabel:'Masque', hostsLabel:'Hôtes disponibles',
    srLabel:(sr,pc) => `${sr} salles (${pc} PC chacune)`,
    vwLabel:(vw)    => `1 réseau admin (${vw} PC)`,
    rsLabel:(rs)    => `1 réseau réserve (${rs} PC)`,
    solHeader:'Toutes les bonnes réponses',
    scorePerfect:(t)   => `🎉 Parfait ! ${t}/${t} !`,
    scoreGood:(c,t)    => `👍 Bien ! ${c}/${t} — regarde les explications.`,
    scoreRetry:(c,t)   => `💪 ${c}/${t} — lis les explications et réessaie !`,
    badgeOk:'✓ Correct', badgeErr:'✗ Faux',
    explainTitle:(ans) => `Bonne réponse : ${ans}`,
    qTexts:[
      'Classe de l\'adresse IP ?',
      'Nombre de sous-réseaux requis (puissance de 2)',
      'Bits empruntés (4e octet)',
      'Adresses hôtes requises',
      'Bits hôtes requis',
      'Longueur de préfixe',
      'Masque de sous-réseau',
      'Total d\'adresses par sous-réseau',
      'Adresses hôtes utilisables',
      'Réseaux théoriquement possibles ?'
    ],
    qPh:['ex. C','ex. 16','ex. 4','ex. 12','ex. 4','ex. /28','ex. 255.255.255.240','ex. 16','ex. 14','ex. 16'],
    solKeys:['Classe','Sous-réseaux','Bits','Hôtes req.','Bits hôtes','Préfixe','Masque','Adr./s-réseau','Hôtes util.','Réseaux'],
    how:[
      {num:'01', title:'Lire',     text:'Observe le réseau et les sous-réseaux.'},
      {num:'02', title:'Saisir',   text:'Remplis les 10 champs.'},
      {num:'03', title:'Vérifier', text:'Une erreur → explication.'},
      {num:'04', title:'Série',    text:'Résous sans erreur.'}
    ],
    footerText:'SubnetMaster — Classe 1aAPC',
  },
  es: {
    dir:'ltr',
    nav:{ trainer:'Entrenador', lernen:'Referencia', anleitung:'Guía' },
    eyebrow:'Entrenador Subnetting',
    title:'Calcular subredes', span:'sin errores.',
    sub:'Practica subnetting con ejercicios aleatorios. Cada error muestra una explicación paso a paso.',
    ctaText:'Iniciar ejercicio',
    slDone:'Ejercicios resueltos', slCorrect:'Respuestas correctas', slPct:'Precisión', slStreak:'Racha',
    lblTask:'Ejercicio actual', lblNetwork:'Red', lblNeeded:'Requerido',
    lblQuestions:'Responder preguntas',
    btnNew:'Nuevo ejercicio', btnCheck:'Comprobar respuestas',
    maskLabel:'Máscara de subred', hostsLabel:'Hosts disponibles',
    srLabel:(sr,pc) => `${sr} aulas (${pc} PC cada una)`,
    vwLabel:(vw)    => `1 red de administración (${vw} PC)`,
    rsLabel:(rs)    => `1 red de reserva (${rs} PC)`,
    solHeader:'Todas las respuestas correctas',
    scorePerfect:(t)   => `🎉 ¡Perfecto! ¡${t}/${t}!`,
    scoreGood:(c,t)    => `👍 ¡Bien! ${c}/${t} — mira las explicaciones.`,
    scoreRetry:(c,t)   => `💪 ${c}/${t} — lee y vuelve a intentarlo.`,
    badgeOk:'✓ Correcto', badgeErr:'✗ Incorrecto',
    explainTitle:(ans) => `Respuesta: ${ans}`,
    qTexts:[
      '¿Clase de la dirección IP?',
      'Subredes requeridas (potencia de 2)',
      'Bits prestados (4.º octeto)',
      'Direcciones de host requeridas',
      'Bits de host requeridos',
      'Longitud de prefijo',
      'Máscara de subred',
      'Total de direcciones por subred',
      'Hosts utilizables por subred',
      '¿Redes teóricamente posibles?'
    ],
    qPh:['p.ej. C','p.ej. 16','p.ej. 4','p.ej. 12','p.ej. 4','p.ej. /28','p.ej. 255.255.255.240','p.ej. 16','p.ej. 14','p.ej. 16'],
    solKeys:['Clase','Subredes','Bits','Hosts req.','Bits host','Prefijo','Máscara','Dir./subred','Hosts util.','Redes teór.'],
    how:[
      {num:'01', title:'Leer',     text:'Observa la red y las subredes.'},
      {num:'02', title:'Ingresar', text:'Rellena los 10 campos.'},
      {num:'03', title:'Verificar',text:'Un error → explicación.'},
      {num:'04', title:'Racha',    text:'Resuelve sin errores.'}
    ],
    footerText:'SubnetMaster — Clase 1aAPC',
  },
};

/* ═══════════════════════════════════════════════════
   PAGE-SPECIFIC TRANSLATIONS (lernen + anleitung)
   ═══════════════════════════════════════════════════ */
const PAGE_TRANS = {
  de: {
    /* ── lernen.html ── */
    'l-hero-eyebrow':'📚 Subnetting Lexikon',
    'l-hero-h1':'Subnetting von Null an verstehen',
    'l-hero-p':'Hier lernst du alles — von IP-Adressen über Binärzahlen bis zum kompletten Subnetting. Mit Diagrammen, Beispielen und einem interaktiven Rechner.',
    'l-nav-1':'Was ist eine IP-Adresse?','l-nav-2':'Binärzahlen','l-nav-3':'IP-Klassen',
    'l-nav-4':'Was ist Subnetting?','l-nav-5':'Subnetzmaske','l-nav-6':'Bits borgen',
    'l-nav-7':'Präfixlänge','l-nav-8':'Subnetz-Tabelle','l-nav-9':'Rechner','l-nav-10':'Schnell-Referenz',
    'l-s1-h2':'01 — Was ist eine IP-Adresse?',
    'l-s1-intro':'Eine IP-Adresse ist wie eine Hausnummer im Internet — sie identifiziert eindeutig ein Gerät im Netzwerk.',
    'l-s1-p1':'IPv4-Adressen bestehen aus <strong>4 Bytes</strong> (= 4 × 8 Bits = 32 Bits), getrennt durch Punkte:',
    'l-s1-diag-title':'Aufbau einer IPv4-Adresse: 192.168.50.1',
    'l-s1-bin-label':'Jedes Byte in Binär (8 Bits):',
    'l-s1-bin-note':'128+64 = <span style="color:var(--accent)">192</span> &nbsp;&nbsp; 128+32+8 = <span style="color:var(--accent)">168</span>',
    'l-s1-tip':'Ein Byte kann Werte von 0 bis 255 speichern (2⁸ = 256 Möglichkeiten). Deshalb sieht man in IP-Adressen nie eine Zahl über 255.',
    'l-s2-h2':'02 — Binärzahlen verstehen',
    'l-s2-intro':'Computer kennen nur 0 und 1. Deshalb musst du für Subnetting verstehen, wie Binärzahlen funktionieren.',
    'l-s2-h3a':'Stellenwerte',
    'l-s2-p1':'Jede Stelle hat einen Wert — eine 2er-Potenz. Von rechts nach links:',
    'l-s2-diag-title':'🔢 Stellenwerte eines Bytes (8 Bits)',
    'l-s2-sum-note':'Nur die 1er addieren: 128 + 64 + 16 = <span style="color:var(--green);font-weight:600">208</span>',
    'l-s2-h3b':'Dezimal → Binär Tabelle',
    'l-s2-th1':'Dezimal','l-s2-th2':'Binär','l-s2-th3':'Erklärung',
    'l-s2-e1':'nur Bit 7','l-s2-e2':'128 + 64','l-s2-e3':'128 + 64 + 32','l-s2-e4':'128+64+32+16','l-s2-e5':'128+64+32+16+8','l-s2-e6':'alle Bits',
    'l-s3-h2':'03 — IP-Klassen',
    'l-s3-intro':'IPv4-Adressen sind in Klassen eingeteilt. Die Klasse bestimmt, wie groß das Netz ist.',
    'l-s3-diag-title':'🏷️ IP-Klassen Übersicht',
    'l-s3-th1':'Klasse','l-s3-th2':'Erstes Byte','l-s3-th3':'Bereich','l-s3-th4':'Netze','l-s3-th5':'Hosts/Netz',
    'l-s3-tip':'<strong>Merkrege:</strong> Klasse C = 192–223 im ersten Byte. Das ist die häufigste Klasse in Schulaufgaben (z.B. 192.168.x.x).',
    'l-s3-h3vis':'Visuell: Wie groß sind die Klassen?',
    'l-s3-class-a':'Klasse A — riesige Netze','l-s3-hosts-a':'16 Millionen Hosts pro Netz',
    'l-s3-class-b':'Klasse B — mittlere Netze','l-s3-hosts-b':'65.534 Hosts pro Netz',
    'l-s3-class-c':'Klasse C — kleine Netze ← wir arbeiten hier','l-s3-hosts-c':'254 Hosts pro Netz',
    'l-s4-h2':'04 — Was ist Subnetting?',
    'l-s4-intro':'Subnetting bedeutet: ein großes Netz in kleinere Teilnetze aufteilen — wie Wände in einem großen Haus einziehen.',
    'l-s4-p1':'Stell dir vor: Du hast ein Bürogebäude (= ein /24 Netz mit 254 Adressen). Du willst für jede Abteilung ein eigenes Netz — damit der Verkehr getrennt bleibt und du weißt, welches Gerät wo ist.',
    'l-s4-diag-title':'🏢 Ein /24 Netz wird aufgeteilt',
    'l-s4-sub-hosts':'14 nutzbare Hosts',
    'l-s4-arrow':'→ Aus einem /24 Netz entstehen durch Subnetting z.B. 16 kleinere /28 Netze.',
    'l-s4-h3why':'Warum Subnetting?',
    'l-s4-c1h':'Ordnung & Struktur','l-s4-c1p':'Jede Abteilung/Raum bekommt ein eigenes Subnetz — klar getrennt und übersichtlich.',
    'l-s4-c2h':'Sicherheit','l-s4-c2p':'Subnetze können voneinander isoliert werden — z.B. darf das Büronetz nicht das Servernetz erreichen.',
    'l-s4-c3h':'Weniger Broadcast-Traffic','l-s4-c3p':'Broadcasts bleiben im Subnetz — das entlastet das gesamte Netz.',
    'l-s5-h2':'05 — Die Subnetzmaske',
    'l-s5-intro':'Die Subnetzmaske zeigt an, welcher Teil der IP-Adresse das <strong>Netz</strong> und welcher Teil der <strong>Host</strong> ist.',
    'l-s5-rule':'Regel: <code>1</code> = Netz-Teil &nbsp;|&nbsp; <code>0</code> = Host-Teil',
    'l-s5-diag1-title':'🎭 Subnetzmaske 255.255.255.0 (/24)',
    'l-s5-ip-label':'IP-Adresse:','l-s5-mask-label':'Subnetzmaske:',
    'l-s5-note':'255 = alle Bits auf 1 → Netz-Teil &nbsp;|&nbsp; 0 = alle Bits auf 0 → Host-Teil',
    'l-s5-diag2-title':'🎭 Subnetzmaske 255.255.255.240 (/28)',
    'l-s5-diag2-p':'Das 4. Byte ist jetzt gemischt — 4 Bits Netz, 4 Bits Host:',
    'l-s6-h2':'06 — Bits borgen',
    'l-s6-intro':'Subnetting funktioniert so: Man nimmt Bits vom Host-Teil und gibt sie dem Netz-Teil. Das erzeugt mehr, aber kleinere Subnetze.',
    'l-s6-diag-title':'🔄 Vorher /24 → Nachher /28 (4 Bits geborgt)',
    'l-s6-before-label':'VORHER — 4. Byte: alles Host-Bits',
    'l-s6-before-note':'8 Host-Bits → 2⁸−2 = 254 Hosts, 1 Netz',
    'l-s6-after-label':'NACHHER — 4 Bits für Subnetze geborgt',
    'l-s6-legend-s':'S = Subnetz-Bit (geborgt)','l-s6-legend-h':'H = Host-Bit (bleibt)',
    'l-s6-after-note':'4 Subnetz-Bits → 2⁴ = <strong style="color:var(--accent)">16 Subnetze</strong><br>4 Host-Bits → 2⁴−2 = <strong style="color:var(--green)">14 nutzbare Hosts</strong> je Subnetz',
    'l-s6-warn':'Mehr geborgene Bits = mehr Subnetze, aber weniger Hosts pro Subnetz. Das ist immer ein Kompromiss!',
    'l-s6-h3':'Die Formel',
    'l-s6-f1l':'Subnetze','l-s6-f1r':'2^(geborgene Bits)',
    'l-s6-f2l':'Hosts pro Subnetz','l-s6-f2r':'2^(verbleibende Bits)','l-s6-f2n':'(−Netz −Broadcast)',
    'l-s7-h2':'07 — Präfixlänge (CIDR)',
    'l-s7-intro':'Die Präfixlänge (z.B. <code>/28</code>) ist eine kompakte Schreibweise für die Subnetzmaske — sie sagt, wie viele Bits das Netz-Teil hat.',
    'l-s7-diag-title':'📐 /28 = 28 Netz-Bits',
    'l-s7-diag-note':'24 fixe Netz-Bits + <span style="color:var(--purple)">4 Subnetz-Bits</span> = <strong style="color:var(--accent)">/28</strong> &nbsp;|&nbsp; 4 Host-Bits bleiben',
    'l-s7-th1':'Präfix','l-s7-th2':'Subnetzmaske','l-s7-th3':'Geborgene Bits','l-s7-th4':'Subnetze','l-s7-th5':'Hosts/Subnetz','l-s7-th6':'Blockgröße',
    'l-s8-h2':'08 — Subnetz-Tabelle erstellen',
    'l-s8-intro':'Wenn du die Blockgröße weißt, kannst du alle Subnetze aufzählen. Blockgröße = Gesamtadressen pro Subnetz.',
    'l-s8-p1':'Beispiel: /28 → Blockgröße = 16. Subnetze beginnen bei 0, 16, 32, 48, ...',
    'l-s8-diag-title':'📋 Subnetz-Tabelle für 192.168.50.0/28',
    'l-s8-th1':'Nr.','l-s8-th2':'Subnetz-ID','l-s8-th3':'Erster Host','l-s8-th4':'Letzter Host','l-s8-th5':'Broadcast',
    'l-s8-h3':'Merkhilfe für jedes Subnetz',
    'l-s8-c1h':'Subnetz-ID','l-s8-c1p':'= Subnetz-Nummer × Blockgröße &nbsp;(0×16=0, 1×16=16, 2×16=32 ...)',
    'l-s8-c2h':'Erster Host','l-s8-c2p':'= Subnetz-ID + 1',
    'l-s8-c3h':'Broadcast','l-s8-c3p':'= Subnetz-ID + Blockgröße − 1 &nbsp;(0+16−1=15)',
    'l-s8-c4h':'Letzter Host','l-s8-c4p':'= Broadcast − 1',
    'l-s9-h2':'09 — Interaktiver Subnetz-Rechner',
    'l-s9-p':'Gib die Anzahl der benötigten Subnetze ein — der Rechner berechnet alles automatisch.',
    'l-s9-label1':'Benötigte Subnetze:','l-s9-label2':'PCs im größten Subnetz:',
    'l-s9-ck1':'Subnetze (2er-Potenz)','l-s9-ck2':'Geborgene Bits','l-s9-ck3':'Host-Bits',
    'l-s9-ck4':'Präfixlänge','l-s9-ck5':'Subnetzmaske','l-s9-ck6':'Adressen/Subnetz',
    'l-s9-ck7':'Nutzbare Hosts','l-s9-ck7-err':'← zu wenig!','l-s9-ck8':'Theor. Netze',
    'l-s10-h2':'10 — Schnell-Referenz',
    'l-s10-h3':'Die 10 Fragen im Überblick',
    'l-s10-th2':'Frage','l-s10-th3':'Formel / Methode',
    'l-s10-aq':'IP-Klasse','l-s10-af':'1. Byte: 1–126=A, 128–191=B, 192–223=C',
    'l-s10-bq':'Benötigte Subnetze','l-s10-bf':'SR + VW + Reserve → nächste 2er-Potenz',
    'l-s10-cq':'Geborgene Bits','l-s10-cf':'2^x = Subnetze → x = ?',
    'l-s10-dq':'Erf. Hostadressen','l-s10-df':'PCs im größten Raum',
    'l-s10-eq':'Hostbits','l-s10-ef':'8 − geborgene Bits',
    'l-s10-fq':'Präfixlänge','l-s10-ff':'/24 + geborgene Bits',
    'l-s10-gq':'Subnetzmaske','l-s10-gf':'4. Byte: Einsen addieren (128+64+32+16=240)',
    'l-s10-hq':'Adressen/Subnetz','l-s10-hf':'2^(Hostbits)',
    'l-s10-iq':'Nutzb. Hosts','l-s10-if':'Adressen/Subnetz − 2',
    'l-s10-jq':'Theor. Netze','l-s10-jf':'2^(geborgene Bits)',
    'l-s10-cta':'Jetzt Trainer öffnen und üben!','l-s10-cta-link':'→ Zum Trainer',
    /* ── anleitung.html ── */
    'a-hero-eyebrow':'📋 Schritt-für-Schritt Anleitung',
    'a-hero-h1':'Wie löse ich eine Subnetting-Aufgabe?',
    'a-hero-p':'Hier findest du den kompletten Lösungsweg — von der Aufgabe bis zu allen 10 Antworten. Mit einem vollständig gelösten Beispiel.',
    'a-section-label':'Der Lösungsweg',
    'a-step1':'Aufgabe lesen und Daten sammeln',
    'a-step2':'a) IP-Klasse bestimmen',
    'a-step3':'b) Benötigte Subnetze berechnen',
    'a-step4':'c) Geborgene Bits bestimmen',
    'a-step5':'d) Erforderliche Hostadressen',
    'a-step6':'e) Hostbits berechnen',
    'a-step7':'f) Präfixlänge berechnen',
    'a-step8':'g) Subnetzmaske berechnen',
    'a-step9':'h & i) Adressen je Subnetz',
    'a-step10':'j) Theoretisch mögliche Netze',
    'a-example-label':'Vollständig gelöstes Beispiel',
    'a-example-task':'Netz: <code>192.168.50.0/24</code><br>Benötigt: 8 Schulungsräume (je 12 PCs) · 1 Verwaltungsnetz (10 PCs) · 1 Reservenetz (4 PCs)',
    'a-example-task-label':'Aufgabe:',
    'a-sq-a':'IP-Klasse','a-sq-b':'Benötigte Subnetze','a-sq-c':'Geborgene Bits',
    'a-sq-d':'Erf. Hostadressen','a-sq-e':'Hostbits','a-sq-f':'Präfixlänge',
    'a-sq-g':'Subnetzmaske','a-sq-h':'Adressen je Subnetz','a-sq-i':'Nutzbare Hosts','a-sq-j':'Theor. Netze',
    'a-btn-practice':'Jetzt üben →','a-btn-review':'📚 Alles nochmal nachlesen',
    /* ── index.html ── */
    'how-label':'So funktioniert es',
    'cls-label':'IP-Klasse:', 'cls-random':'Zufällig', 'cls-a':'Klasse A', 'cls-b':'Klasse B', 'cls-c':'Klasse C',
  },
  en: {
    'l-hero-eyebrow':'📚 Subnetting Reference',
    'l-hero-h1':'Understand subnetting from scratch',
    'l-hero-p':'Learn everything here — from IP addresses and binary numbers to complete subnetting. With diagrams, examples and an interactive calculator.',
    'l-nav-1':'What is an IP address?','l-nav-2':'Binary numbers','l-nav-3':'IP classes',
    'l-nav-4':'What is subnetting?','l-nav-5':'Subnet mask','l-nav-6':'Borrowing bits',
    'l-nav-7':'Prefix length','l-nav-8':'Subnet table','l-nav-9':'Calculator','l-nav-10':'Quick reference',
    'l-s1-h2':'01 — What is an IP address?',
    'l-s1-intro':'An IP address is like a house number on the internet — it uniquely identifies a device on the network.',
    'l-s1-p1':'IPv4 addresses consist of <strong>4 bytes</strong> (= 4 × 8 bits = 32 bits), separated by dots:',
    'l-s1-diag-title':'Structure of an IPv4 address: 192.168.50.1',
    'l-s1-bin-label':'Each byte in binary (8 bits):',
    'l-s1-bin-note':'128+64 = <span style="color:var(--accent)">192</span> &nbsp;&nbsp; 128+32+8 = <span style="color:var(--accent)">168</span>',
    'l-s1-tip':'A byte can store values from 0 to 255 (2⁸ = 256 possibilities). That\'s why you never see a number above 255 in IP addresses.',
    'l-s2-h2':'02 — Understanding binary numbers',
    'l-s2-intro':'Computers only know 0 and 1. That\'s why you need to understand how binary numbers work for subnetting.',
    'l-s2-h3a':'Place values',
    'l-s2-p1':'Each position has a value — a power of 2. From right to left:',
    'l-s2-diag-title':'🔢 Place values of a byte (8 bits)',
    'l-s2-sum-note':'Add only the 1s: 128 + 64 + 16 = <span style="color:var(--green);font-weight:600">208</span>',
    'l-s2-h3b':'Decimal → Binary table',
    'l-s2-th1':'Decimal','l-s2-th2':'Binary','l-s2-th3':'Explanation',
    'l-s2-e1':'bit 7 only','l-s2-e2':'128 + 64','l-s2-e3':'128 + 64 + 32','l-s2-e4':'128+64+32+16','l-s2-e5':'128+64+32+16+8','l-s2-e6':'all bits',
    'l-s3-h2':'03 — IP classes',
    'l-s3-intro':'IPv4 addresses are divided into classes. The class determines how large the network is.',
    'l-s3-diag-title':'🏷️ IP classes overview',
    'l-s3-th1':'Class','l-s3-th2':'First byte','l-s3-th3':'Range','l-s3-th4':'Networks','l-s3-th5':'Hosts/Net',
    'l-s3-tip':'<strong>Memory aid:</strong> Class C = 192–223 in the first byte. This is the most common class in school exercises (e.g. 192.168.x.x).',
    'l-s3-h3vis':'Visual: How large are the classes?',
    'l-s3-class-a':'Class A — huge networks','l-s3-hosts-a':'16 million hosts per network',
    'l-s3-class-b':'Class B — medium networks','l-s3-hosts-b':'65,534 hosts per network',
    'l-s3-class-c':'Class C — small networks ← we work here','l-s3-hosts-c':'254 hosts per network',
    'l-s4-h2':'04 — What is subnetting?',
    'l-s4-intro':'Subnetting means dividing a large network into smaller subnetworks — like building walls inside a large house.',
    'l-s4-p1':'Imagine: you have an office building (= a /24 network with 254 addresses). You want a separate network for each department — so traffic stays separated and you know which device is where.',
    'l-s4-diag-title':'🏢 A /24 network is divided',
    'l-s4-sub-hosts':'14 usable hosts',
    'l-s4-arrow':'→ From one /24 network, subnetting creates e.g. 16 smaller /28 networks.',
    'l-s4-h3why':'Why subnetting?',
    'l-s4-c1h':'Order & structure','l-s4-c1p':'Each department/room gets its own subnet — clearly separated and organized.',
    'l-s4-c2h':'Security','l-s4-c2p':'Subnets can be isolated from each other — e.g. the office network cannot reach the server network.',
    'l-s4-c3h':'Less broadcast traffic','l-s4-c3p':'Broadcasts stay within the subnet — relieving the entire network.',
    'l-s5-h2':'05 — The subnet mask',
    'l-s5-intro':'The subnet mask shows which part of the IP address is the <strong>network</strong> and which part is the <strong>host</strong>.',
    'l-s5-rule':'Rule: <code>1</code> = network part &nbsp;|&nbsp; <code>0</code> = host part',
    'l-s5-diag1-title':'🎭 Subnet mask 255.255.255.0 (/24)',
    'l-s5-ip-label':'IP address:','l-s5-mask-label':'Subnet mask:',
    'l-s5-note':'255 = all bits set to 1 → network part &nbsp;|&nbsp; 0 = all bits set to 0 → host part',
    'l-s5-diag2-title':'🎭 Subnet mask 255.255.255.240 (/28)',
    'l-s5-diag2-p':'The 4th byte is now mixed — 4 bits network, 4 bits host:',
    'l-s6-h2':'06 — Borrowing bits',
    'l-s6-intro':'Subnetting works like this: you take bits from the host part and give them to the network part. This creates more, but smaller, subnets.',
    'l-s6-diag-title':'🔄 Before /24 → After /28 (4 bits borrowed)',
    'l-s6-before-label':'BEFORE — 4th byte: all host bits',
    'l-s6-before-note':'8 host bits → 2⁸−2 = 254 hosts, 1 network',
    'l-s6-after-label':'AFTER — 4 bits borrowed for subnets',
    'l-s6-legend-s':'S = Subnet bit (borrowed)','l-s6-legend-h':'H = Host bit (remains)',
    'l-s6-after-note':'4 subnet bits → 2⁴ = <strong style="color:var(--accent)">16 subnets</strong><br>4 host bits → 2⁴−2 = <strong style="color:var(--green)">14 usable hosts</strong> per subnet',
    'l-s6-warn':'More borrowed bits = more subnets, but fewer hosts per subnet. It\'s always a trade-off!',
    'l-s6-h3':'The formula',
    'l-s6-f1l':'Subnets','l-s6-f1r':'2^(borrowed bits)',
    'l-s6-f2l':'Hosts per subnet','l-s6-f2r':'2^(remaining bits)','l-s6-f2n':'(−network −broadcast)',
    'l-s7-h2':'07 — Prefix length (CIDR)',
    'l-s7-intro':'The prefix length (e.g. <code>/28</code>) is a compact notation for the subnet mask — it says how many bits the network part has.',
    'l-s7-diag-title':'📐 /28 = 28 network bits',
    'l-s7-diag-note':'24 fixed network bits + <span style="color:var(--purple)">4 subnet bits</span> = <strong style="color:var(--accent)">/28</strong> &nbsp;|&nbsp; 4 host bits remain',
    'l-s7-th1':'Prefix','l-s7-th2':'Subnet mask','l-s7-th3':'Borrowed bits','l-s7-th4':'Subnets','l-s7-th5':'Hosts/Subnet','l-s7-th6':'Block size',
    'l-s8-h2':'08 — Creating a subnet table',
    'l-s8-intro':'Once you know the block size, you can list all subnets. Block size = total addresses per subnet.',
    'l-s8-p1':'Example: /28 → block size = 16. Subnets start at 0, 16, 32, 48, ...',
    'l-s8-diag-title':'📋 Subnet table for 192.168.50.0/28',
    'l-s8-th1':'No.','l-s8-th2':'Subnet-ID','l-s8-th3':'First host','l-s8-th4':'Last host','l-s8-th5':'Broadcast',
    'l-s8-h3':'Memory aid for each subnet',
    'l-s8-c1h':'Subnet-ID','l-s8-c1p':'= subnet number × block size (0×16=0, 1×16=16, 2×16=32 ...)',
    'l-s8-c2h':'First host','l-s8-c2p':'= Subnet-ID + 1',
    'l-s8-c3h':'Broadcast','l-s8-c3p':'= Subnet-ID + block size − 1 (0+16−1=15)',
    'l-s8-c4h':'Last host','l-s8-c4p':'= Broadcast − 1',
    'l-s9-h2':'09 — Interactive subnet calculator',
    'l-s9-p':'Enter the number of required subnets — the calculator computes everything automatically.',
    'l-s9-label1':'Required subnets:','l-s9-label2':'PCs in the largest subnet:',
    'l-s9-ck1':'Subnets (power of 2)','l-s9-ck2':'Borrowed bits','l-s9-ck3':'Host bits',
    'l-s9-ck4':'Prefix length','l-s9-ck5':'Subnet mask','l-s9-ck6':'Addresses/subnet',
    'l-s9-ck7':'Usable hosts','l-s9-ck7-err':'← too few!','l-s9-ck8':'Theor. networks',
    'l-s10-h2':'10 — Quick reference',
    'l-s10-h3':'Overview of the 10 questions',
    'l-s10-th2':'Question','l-s10-th3':'Formula / Method',
    'l-s10-aq':'IP class','l-s10-af':'1st byte: 1–126=A, 128–191=B, 192–223=C',
    'l-s10-bq':'Required subnets','l-s10-bf':'SR + VW + Reserve → next power of 2',
    'l-s10-cq':'Borrowed bits','l-s10-cf':'2^x = subnets → x = ?',
    'l-s10-dq':'Req. host addresses','l-s10-df':'PCs in the largest room',
    'l-s10-eq':'Host bits','l-s10-ef':'8 − borrowed bits',
    'l-s10-fq':'Prefix length','l-s10-ff':'/24 + borrowed bits',
    'l-s10-gq':'Subnet mask','l-s10-gf':'4th byte: add ones (128+64+32+16=240)',
    'l-s10-hq':'Addresses/subnet','l-s10-hf':'2^(host bits)',
    'l-s10-iq':'Usable hosts','l-s10-if':'Addresses/subnet − 2',
    'l-s10-jq':'Theor. networks','l-s10-jf':'2^(borrowed bits)',
    'l-s10-cta':'Open the trainer and practice now!','l-s10-cta-link':'→ To the trainer',
    'a-hero-eyebrow':'📋 Step-by-step guide',
    'a-hero-h1':'How do I solve a subnetting task?',
    'a-hero-p':'Here you find the complete solution path — from the task to all 10 answers. With a fully solved example.',
    'a-section-label':'The solution path',
    'a-step1':'Read the task and gather data',
    'a-step2':'a) Determine IP class',
    'a-step3':'b) Calculate required subnets',
    'a-step4':'c) Determine borrowed bits',
    'a-step5':'d) Required host addresses',
    'a-step6':'e) Calculate host bits',
    'a-step7':'f) Calculate prefix length',
    'a-step8':'g) Calculate subnet mask',
    'a-step9':'h & i) Addresses per subnet',
    'a-step10':'j) Theoretically possible networks',
    'a-example-label':'Fully solved example',
    'a-example-task':'Network: <code>192.168.50.0/24</code><br>Required: 8 training rooms (12 PCs each) · 1 admin network (10 PCs) · 1 reserve network (4 PCs)',
    'a-example-task-label':'Task:',
    'a-sq-a':'IP class','a-sq-b':'Required subnets','a-sq-c':'Borrowed bits',
    'a-sq-d':'Req. host addresses','a-sq-e':'Host bits','a-sq-f':'Prefix length',
    'a-sq-g':'Subnet mask','a-sq-h':'Addresses per subnet','a-sq-i':'Usable hosts','a-sq-j':'Theor. networks',
    'a-btn-practice':'Practice now →','a-btn-review':'📚 Read the reference again',
    'how-label':'How it works',
    'cls-label':'IP class:', 'cls-random':'Random', 'cls-a':'Class A', 'cls-b':'Class B', 'cls-c':'Class C',
  },
  ar: {
    'l-hero-eyebrow':'📚 قاموس الشبكات',
    'l-hero-h1':'افهم تقسيم الشبكات من الصفر',
    'l-hero-p':'تعلم كل شيء هنا — من عناوين IP والأرقام الثنائية إلى تقسيم الشبكات الكامل. مع مخططات وأمثلة وحاسبة تفاعلية.',
    'l-nav-1':'ما هو عنوان IP؟','l-nav-2':'الأرقام الثنائية','l-nav-3':'فئات IP',
    'l-nav-4':'ما هو تقسيم الشبكات؟','l-nav-5':'قناع الشبكة','l-nav-6':'استعارة البتات',
    'l-nav-7':'طول البادئة','l-nav-8':'جدول الشبكات','l-nav-9':'الحاسبة','l-nav-10':'مرجع سريع',
    'l-s1-h2':'01 — ما هو عنوان IP؟',
    'l-s1-intro':'عنوان IP مثل رقم المنزل على الإنترنت — يُعرّف الجهاز بشكل فريد على الشبكة.',
    'l-s1-p1':'تتكون عناوين IPv4 من <strong>4 بايت</strong> (= 4 × 8 بت = 32 بت)، مفصولة بنقاط:',
    'l-s1-diag-title':'بنية عنوان IPv4: 192.168.50.1',
    'l-s1-bin-label':'كل بايت بالنظام الثنائي (8 بت):',
    'l-s1-bin-note':'128+64 = <span style="color:var(--accent)">192</span> &nbsp;&nbsp; 128+32+8 = <span style="color:var(--accent)">168</span>',
    'l-s1-tip':'يمكن للبايت تخزين قيم من 0 إلى 255 (2⁸ = 256 احتمالاً). لهذا لا ترى أبداً رقماً أكبر من 255 في عناوين IP.',
    'l-s2-h2':'02 — فهم الأرقام الثنائية',
    'l-s2-intro':'الحواسيب تعرف فقط 0 و 1. لذا تحتاج لفهم كيف تعمل الأرقام الثنائية في تقسيم الشبكات.',
    'l-s2-h3a':'قيم المراتب',
    'l-s2-p1':'كل مرتبة لها قيمة — قوة للعدد 2. من اليمين إلى اليسار:',
    'l-s2-diag-title':'🔢 قيم مراتب البايت (8 بت)',
    'l-s2-sum-note':'أجمع فقط الـ 1: 128 + 64 + 16 = <span style="color:var(--green);font-weight:600">208</span>',
    'l-s2-h3b':'جدول عشري → ثنائي',
    'l-s2-th1':'عشري','l-s2-th2':'ثنائي','l-s2-th3':'الشرح',
    'l-s2-e1':'البت 7 فقط','l-s2-e2':'128 + 64','l-s2-e3':'128 + 64 + 32','l-s2-e4':'128+64+32+16','l-s2-e5':'128+64+32+16+8','l-s2-e6':'كل البتات',
    'l-s3-h2':'03 — فئات IP',
    'l-s3-intro':'عناوين IPv4 مقسمة إلى فئات. الفئة تحدد حجم الشبكة.',
    'l-s3-diag-title':'🏷️ نظرة عامة على فئات IP',
    'l-s3-th1':'الفئة','l-s3-th2':'البايت الأول','l-s3-th3':'النطاق','l-s3-th4':'الشبكات','l-s3-th5':'مضيفون/شبكة',
    'l-s3-tip':'<strong>قاعدة حفظ:</strong> الفئة C = 192–223 في البايت الأول. هذه أكثر فئة شائعة في تمارين المدرسة (مثلاً 192.168.x.x).',
    'l-s3-h3vis':'بصرياً: ما حجم الفئات؟',
    'l-s3-class-a':'الفئة A — شبكات ضخمة','l-s3-hosts-a':'16 مليون مضيف لكل شبكة',
    'l-s3-class-b':'الفئة B — شبكات متوسطة','l-s3-hosts-b':'65.534 مضيف لكل شبكة',
    'l-s3-class-c':'الفئة C — شبكات صغيرة ← نعمل هنا','l-s3-hosts-c':'254 مضيف لكل شبكة',
    'l-s4-h2':'04 — ما هو تقسيم الشبكات؟',
    'l-s4-intro':'تقسيم الشبكات يعني: تقسيم شبكة كبيرة إلى شبكات فرعية أصغر — مثل بناء جدران داخل منزل كبير.',
    'l-s4-p1':'تخيل: لديك مبنى مكاتب (= شبكة /24 بـ 254 عنواناً). تريد شبكة منفصلة لكل قسم — حتى تبقى حركة البيانات منفصلة وتعرف أين كل جهاز.',
    'l-s4-diag-title':'🏢 تقسيم شبكة /24',
    'l-s4-sub-hosts':'14 مضيفاً صالحاً',
    'l-s4-arrow':'→ من شبكة /24 واحدة، ينشئ التقسيم مثلاً 16 شبكة /28 أصغر.',
    'l-s4-h3why':'لماذا تقسيم الشبكات؟',
    'l-s4-c1h':'النظام والترتيب','l-s4-c1p':'كل قسم/غرفة تحصل على شبكتها الفرعية — منفصلة بوضوح ومنظمة.',
    'l-s4-c2h':'الأمان','l-s4-c2p':'يمكن عزل الشبكات الفرعية — مثلاً شبكة المكاتب لا تصل لشبكة الخوادم.',
    'l-s4-c3h':'تقليل حركة البث','l-s4-c3p':'البث يبقى داخل الشبكة الفرعية — مما يخفف الحمل على الشبكة.',
    'l-s5-h2':'05 — قناع الشبكة الفرعية',
    'l-s5-intro':'قناع الشبكة يُظهر أي جزء من عنوان IP هو <strong>الشبكة</strong> وأيها <strong>المضيف</strong>.',
    'l-s5-rule':'القاعدة: <code>1</code> = جزء الشبكة &nbsp;|&nbsp; <code>0</code> = جزء المضيف',
    'l-s5-diag1-title':'🎭 قناع الشبكة 255.255.255.0 (/24)',
    'l-s5-ip-label':'عنوان IP:','l-s5-mask-label':'قناع الشبكة:',
    'l-s5-note':'255 = كل البتات 1 → جزء الشبكة &nbsp;|&nbsp; 0 = كل البتات 0 → جزء المضيف',
    'l-s5-diag2-title':'🎭 قناع الشبكة 255.255.255.240 (/28)',
    'l-s5-diag2-p':'البايت الرابع الآن مختلط — 4 بت للشبكة، 4 بت للمضيف:',
    'l-s6-h2':'06 — استعارة البتات',
    'l-s6-intro':'تقسيم الشبكات يعمل هكذا: تأخذ بتات من جزء المضيف وتعطيها لجزء الشبكة. هذا ينشئ شبكات فرعية أكثر لكن أصغر.',
    'l-s6-diag-title':'🔄 قبل /24 → بعد /28 (4 بتات مستعارة)',
    'l-s6-before-label':'قبل — البايت الرابع: كلها بتات مضيف',
    'l-s6-before-note':'8 بتات مضيف → 2⁸−2 = 254 مضيفاً، شبكة 1',
    'l-s6-after-label':'بعد — 4 بتات مستعارة للشبكات الفرعية',
    'l-s6-legend-s':'S = بت الشبكة الفرعية (مستعار)','l-s6-legend-h':'H = بت المضيف (يبقى)',
    'l-s6-after-note':'4 بتات شبكة → 2⁴ = <strong style="color:var(--accent)">16 شبكة فرعية</strong><br>4 بتات مضيف → 2⁴−2 = <strong style="color:var(--green)">14 مضيفاً صالحاً</strong> لكل شبكة',
    'l-s6-warn':'المزيد من البتات المستعارة = شبكات فرعية أكثر، لكن مضيفون أقل لكل شبكة. إنها دائماً مقايضة!',
    'l-s6-h3':'الصيغة',
    'l-s6-f1l':'الشبكات الفرعية','l-s6-f1r':'2^(البتات المستعارة)',
    'l-s6-f2l':'مضيفون لكل شبكة','l-s6-f2r':'2^(البتات المتبقية)','l-s6-f2n':'(−الشبكة −البث)',
    'l-s7-h2':'07 — طول البادئة (CIDR)',
    'l-s7-intro':'طول البادئة (مثلاً <code>/28</code>) هو تدوين مختصر للقناع — يُخبرنا بعدد بتات جزء الشبكة.',
    'l-s7-diag-title':'📐 /28 = 28 بت شبكة',
    'l-s7-diag-note':'24 بت شبكة ثابت + <span style="color:var(--purple)">4 بتات شبكة فرعية</span> = <strong style="color:var(--accent)">/28</strong> &nbsp;|&nbsp; 4 بتات مضيف تبقى',
    'l-s7-th1':'البادئة','l-s7-th2':'قناع الشبكة','l-s7-th3':'بتات مستعارة','l-s7-th4':'الشبكات الفرعية','l-s7-th5':'مضيفون/شبكة','l-s7-th6':'حجم الكتلة',
    'l-s8-h2':'08 — إنشاء جدول الشبكات الفرعية',
    'l-s8-intro':'بمجرد معرفة حجم الكتلة، يمكنك سرد جميع الشبكات الفرعية. حجم الكتلة = إجمالي العناوين لكل شبكة.',
    'l-s8-p1':'مثال: /28 → حجم الكتلة = 16. تبدأ الشبكات الفرعية عند 0، 16، 32، 48، ...',
    'l-s8-diag-title':'📋 جدول الشبكات لـ 192.168.50.0/28',
    'l-s8-th1':'الرقم','l-s8-th2':'معرّف الشبكة','l-s8-th3':'أول مضيف','l-s8-th4':'آخر مضيف','l-s8-th5':'البث',
    'l-s8-h3':'مساعدة ذاكرة لكل شبكة فرعية',
    'l-s8-c1h':'معرّف الشبكة','l-s8-c1p':'= رقم الشبكة × حجم الكتلة (0×16=0، 1×16=16، 2×16=32 ...)',
    'l-s8-c2h':'أول مضيف','l-s8-c2p':'= معرّف الشبكة + 1',
    'l-s8-c3h':'البث','l-s8-c3p':'= معرّف الشبكة + حجم الكتلة − 1 (0+16−1=15)',
    'l-s8-c4h':'آخر مضيف','l-s8-c4p':'= البث − 1',
    'l-s9-h2':'09 — حاسبة الشبكات التفاعلية',
    'l-s9-p':'أدخل عدد الشبكات الفرعية المطلوبة — الحاسبة تحسب كل شيء تلقائياً.',
    'l-s9-label1':'الشبكات الفرعية المطلوبة:','l-s9-label2':'أجهزة في أكبر شبكة:',
    'l-s9-ck1':'الشبكات (قوة 2)','l-s9-ck2':'بتات مستعارة','l-s9-ck3':'بتات مضيف',
    'l-s9-ck4':'طول البادئة','l-s9-ck5':'قناع الشبكة','l-s9-ck6':'عناوين/شبكة',
    'l-s9-ck7':'مضيفون صالحون','l-s9-ck7-err':'← قليل جداً!','l-s9-ck8':'شبكات نظرية',
    'l-s10-h2':'10 — مرجع سريع',
    'l-s10-h3':'نظرة عامة على الأسئلة العشرة',
    'l-s10-th2':'السؤال','l-s10-th3':'الصيغة / الطريقة',
    'l-s10-aq':'فئة IP','l-s10-af':'البايت الأول: 1–126=A، 128–191=B، 192–223=C',
    'l-s10-bq':'الشبكات المطلوبة','l-s10-bf':'SR + VW + Reserve → القوة التالية لـ 2',
    'l-s10-cq':'البتات المستعارة','l-s10-cf':'2^x = الشبكات → x = ?',
    'l-s10-dq':'عناوين المضيف المطلوبة','l-s10-df':'أجهزة في أكبر غرفة',
    'l-s10-eq':'بتات المضيف','l-s10-ef':'8 − البتات المستعارة',
    'l-s10-fq':'طول البادئة','l-s10-ff':'/24 + البتات المستعارة',
    'l-s10-gq':'قناع الشبكة','l-s10-gf':'البايت الرابع: جمع الآحاد (128+64+32+16=240)',
    'l-s10-hq':'عناوين/شبكة','l-s10-hf':'2^(بتات المضيف)',
    'l-s10-iq':'مضيفون صالحون','l-s10-if':'عناوين/شبكة − 2',
    'l-s10-jq':'شبكات نظرية','l-s10-jf':'2^(البتات المستعارة)',
    'l-s10-cta':'افتح المدرب وتدرب الآن!','l-s10-cta-link':'→ للمدرب',
    'a-hero-eyebrow':'📋 دليل خطوة بخطوة',
    'a-hero-h1':'كيف أحل مسألة تقسيم الشبكات؟',
    'a-hero-p':'هنا تجد مسار الحل الكامل — من المسألة إلى جميع الإجابات العشر. مع مثال محلول بالكامل.',
    'a-section-label':'مسار الحل',
    'a-step1':'اقرأ المهمة واجمع البيانات','a-step2':'a) تحديد فئة IP',
    'a-step3':'b) حساب الشبكات الفرعية المطلوبة','a-step4':'c) تحديد البتات المستعارة',
    'a-step5':'d) عناوين المضيف المطلوبة','a-step6':'e) حساب بتات المضيف',
    'a-step7':'f) حساب طول البادئة','a-step8':'g) حساب قناع الشبكة',
    'a-step9':'h & i) العناوين لكل شبكة فرعية','a-step10':'j) الشبكات الممكنة نظرياً',
    'a-example-label':'مثال محلول بالكامل',
    'a-example-task':'الشبكة: <code>192.168.50.0/24</code><br>المطلوب: 8 غرف تدريب (12 جهاز لكل غرفة) · 1 شبكة إدارة (10 أجهزة) · 1 شبكة احتياطية (4 أجهزة)',
    'a-example-task-label':'المسألة:',
    'a-sq-a':'فئة IP','a-sq-b':'الشبكات المطلوبة','a-sq-c':'البتات المستعارة',
    'a-sq-d':'عناوين المضيف المطلوبة','a-sq-e':'بتات المضيف','a-sq-f':'طول البادئة',
    'a-sq-g':'قناع الشبكة','a-sq-h':'عناوين لكل شبكة','a-sq-i':'مضيفون صالحون','a-sq-j':'شبكات نظرية',
    'a-btn-practice':'تدرب الآن →','a-btn-review':'📚 اقرأ المرجع مرة أخرى',
    'how-label':'كيف يعمل',
    'cls-label':'فئة IP:', 'cls-random':'عشوائي', 'cls-a':'الفئة A', 'cls-b':'الفئة B', 'cls-c':'الفئة C',
  },
  tr: {
    'l-hero-eyebrow':'📚 Alt Ağ Sözlüğü',
    'l-hero-h1':'Alt ağlamayı sıfırdan anla',
    'l-hero-p':'Her şeyi burada öğren — IP adreslerinden ikili sayılara ve tam alt ağlamaya kadar. Diyagramlar, örnekler ve interaktif hesaplayıcı ile.',
    'l-nav-1':'IP adresi nedir?','l-nav-2':'İkili sayılar','l-nav-3':'IP sınıfları',
    'l-nav-4':'Alt ağlama nedir?','l-nav-5':'Alt ağ maskesi','l-nav-6':'Bit ödünç alma',
    'l-nav-7':'Önek uzunluğu','l-nav-8':'Alt ağ tablosu','l-nav-9':'Hesaplayıcı','l-nav-10':'Hızlı referans',
    'l-s1-h2':'01 — IP adresi nedir?',
    'l-s1-intro':'Bir IP adresi internetteki ev numarası gibidir — bir ağdaki cihazı benzersiz şekilde tanımlar.',
    'l-s1-p1':'IPv4 adresleri nokta ile ayrılmış <strong>4 byte</strong>tan oluşur (= 4 × 8 bit = 32 bit):',
    'l-s1-diag-title':'Bir IPv4 adresinin yapısı: 192.168.50.1',
    'l-s1-bin-label':'Her byte ikili sistemde (8 bit):',
    'l-s1-bin-note':'128+64 = <span style="color:var(--accent)">192</span> &nbsp;&nbsp; 128+32+8 = <span style="color:var(--accent)">168</span>',
    'l-s1-tip':'Bir byte 0 ile 255 arasında değerler saklayabilir (2⁸ = 256 olasılık). Bu yüzden IP adreslerinde 255\'ten büyük sayı göremezsin.',
    'l-s2-h2':'02 — İkili sayıları anlamak',
    'l-s2-intro':'Bilgisayarlar sadece 0 ve 1 bilir. Bu yüzden alt ağlama için ikili sayıların nasıl çalıştığını anlamalısın.',
    'l-s2-h3a':'Basamak değerleri',
    'l-s2-p1':'Her basamağın bir değeri vardır — 2\'nin kuvveti. Sağdan sola:',
    'l-s2-diag-title':'🔢 Bir byte\'ın basamak değerleri (8 bit)',
    'l-s2-sum-note':'Sadece 1\'leri topla: 128 + 64 + 16 = <span style="color:var(--green);font-weight:600">208</span>',
    'l-s2-h3b':'Onluk → İkili Tablo',
    'l-s2-th1':'Onluk','l-s2-th2':'İkili','l-s2-th3':'Açıklama',
    'l-s2-e1':'yalnızca bit 7','l-s2-e2':'128 + 64','l-s2-e3':'128 + 64 + 32','l-s2-e4':'128+64+32+16','l-s2-e5':'128+64+32+16+8','l-s2-e6':'tüm bitler',
    'l-s3-h2':'03 — IP Sınıfları',
    'l-s3-intro':'IPv4 adresleri sınıflara ayrılır. Sınıf, ağın büyüklüğünü belirler.',
    'l-s3-diag-title':'🏷️ IP Sınıfları Özeti',
    'l-s3-th1':'Sınıf','l-s3-th2':'İlk byte','l-s3-th3':'Aralık','l-s3-th4':'Ağlar','l-s3-th5':'Host/Ağ',
    'l-s3-tip':'<strong>Hatırlatma:</strong> C Sınıfı = ilk byte\'ta 192–223. Okul ödevlerinde en yaygın sınıf (örn. 192.168.x.x).',
    'l-s3-h3vis':'Görsel: Sınıflar ne kadar büyük?',
    'l-s3-class-a':'Sınıf A — devasa ağlar','l-s3-hosts-a':'Ağ başına 16 milyon host',
    'l-s3-class-b':'Sınıf B — orta ağlar','l-s3-hosts-b':'Ağ başına 65.534 host',
    'l-s3-class-c':'Sınıf C — küçük ağlar ← burada çalışıyoruz','l-s3-hosts-c':'Ağ başına 254 host',
    'l-s4-h2':'04 — Alt ağlama nedir?',
    'l-s4-intro':'Alt ağlama: büyük bir ağı daha küçük alt ağlara bölmek demektir — büyük bir evde duvar inşa etmek gibi.',
    'l-s4-p1':'Hayal et: Bir ofis binan var (= 254 adresli bir /24 ağı). Her departman için ayrı bir ağ istiyorsun — trafik ayrı kalsın ve hangi cihazın nerede olduğunu bilesin.',
    'l-s4-diag-title':'🏢 Bir /24 ağı bölünüyor',
    'l-s4-sub-hosts':'14 kullanılabilir host',
    'l-s4-arrow':'→ Bir /24 ağından alt ağlama ile örn. 16 küçük /28 ağı oluşturulur.',
    'l-s4-h3why':'Neden alt ağlama?',
    'l-s4-c1h':'Düzen & yapı','l-s4-c1p':'Her departman/oda kendi alt ağını alır — açıkça ayrılmış ve düzenli.',
    'l-s4-c2h':'Güvenlik','l-s4-c2p':'Alt ağlar birbirinden izole edilebilir — örn. ofis ağı sunucu ağına erişemez.',
    'l-s4-c3h':'Daha az yayın trafiği','l-s4-c3p':'Yayınlar alt ağ içinde kalır — tüm ağın yükünü azaltır.',
    'l-s5-h2':'05 — Alt ağ maskesi',
    'l-s5-intro':'Alt ağ maskesi IP adresinin hangi kısmının <strong>ağ</strong> ve hangi kısmının <strong>host</strong> olduğunu gösterir.',
    'l-s5-rule':'Kural: <code>1</code> = ağ kısmı &nbsp;|&nbsp; <code>0</code> = host kısmı',
    'l-s5-diag1-title':'🎭 Alt ağ maskesi 255.255.255.0 (/24)',
    'l-s5-ip-label':'IP adresi:','l-s5-mask-label':'Alt ağ maskesi:',
    'l-s5-note':'255 = tüm bitler 1 → ağ kısmı &nbsp;|&nbsp; 0 = tüm bitler 0 → host kısmı',
    'l-s5-diag2-title':'🎭 Alt ağ maskesi 255.255.255.240 (/28)',
    'l-s5-diag2-p':'4. byte artık karışık — 4 bit ağ, 4 bit host:',
    'l-s6-h2':'06 — Bit ödünç alma',
    'l-s6-intro':'Alt ağlama şöyle çalışır: host kısmından bit alıp ağ kısmına verirsin. Bu daha fazla ama daha küçük alt ağlar oluşturur.',
    'l-s6-diag-title':'🔄 Önce /24 → Sonra /28 (4 bit ödünç alındı)',
    'l-s6-before-label':'ÖNCE — 4. byte: tümü host bitleri',
    'l-s6-before-note':'8 host biti → 2⁸−2 = 254 host, 1 ağ',
    'l-s6-after-label':'SONRA — 4 bit alt ağlar için ödünç alındı',
    'l-s6-legend-s':'S = Alt ağ biti (ödünç)','l-s6-legend-h':'H = Host biti (kalır)',
    'l-s6-after-note':'4 alt ağ biti → 2⁴ = <strong style="color:var(--accent)">16 alt ağ</strong><br>4 host biti → 2⁴−2 = <strong style="color:var(--green)">14 kullanılabilir host</strong> her alt ağda',
    'l-s6-warn':'Daha fazla ödünç bit = daha fazla alt ağ, ama daha az host. Bu her zaman bir ödünleşimdir!',
    'l-s6-h3':'Formül',
    'l-s6-f1l':'Alt ağlar','l-s6-f1r':'2^(ödünç bitler)',
    'l-s6-f2l':'Alt ağ başına host','l-s6-f2r':'2^(kalan bitler)','l-s6-f2n':'(−ağ −yayın)',
    'l-s7-h2':'07 — Önek uzunluğu (CIDR)',
    'l-s7-intro':'Önek uzunluğu (örn. <code>/28</code>) alt ağ maskesi için kompakt bir yazımdır — ağ kısmının kaç bit olduğunu söyler.',
    'l-s7-diag-title':'📐 /28 = 28 ağ biti',
    'l-s7-diag-note':'24 sabit ağ biti + <span style="color:var(--purple)">4 alt ağ biti</span> = <strong style="color:var(--accent)">/28</strong> &nbsp;|&nbsp; 4 host biti kalır',
    'l-s7-th1':'Önek','l-s7-th2':'Alt ağ maskesi','l-s7-th3':'Ödünç bitler','l-s7-th4':'Alt ağlar','l-s7-th5':'Host/Alt ağ','l-s7-th6':'Blok boyutu',
    'l-s8-h2':'08 — Alt ağ tablosu oluşturma',
    'l-s8-intro':'Blok boyutunu bildiğinde tüm alt ağları sıralayabilirsin. Blok boyutu = alt ağ başına toplam adres.',
    'l-s8-p1':'Örnek: /28 → blok boyutu = 16. Alt ağlar 0, 16, 32, 48, ... ile başlar.',
    'l-s8-diag-title':'📋 192.168.50.0/28 için alt ağ tablosu',
    'l-s8-th1':'No.','l-s8-th2':'Alt ağ-ID','l-s8-th3':'İlk host','l-s8-th4':'Son host','l-s8-th5':'Yayın',
    'l-s8-h3':'Her alt ağ için hatırlatma',
    'l-s8-c1h':'Alt ağ-ID','l-s8-c1p':'= alt ağ numarası × blok boyutu (0×16=0, 1×16=16, 2×16=32 ...)',
    'l-s8-c2h':'İlk host','l-s8-c2p':'= Alt ağ-ID + 1',
    'l-s8-c3h':'Yayın adresi','l-s8-c3p':'= Alt ağ-ID + blok boyutu − 1 (0+16−1=15)',
    'l-s8-c4h':'Son host','l-s8-c4p':'= Yayın − 1',
    'l-s9-h2':'09 — İnteraktif alt ağ hesaplayıcısı',
    'l-s9-p':'Gerekli alt ağ sayısını gir — hesaplayıcı her şeyi otomatik hesaplar.',
    'l-s9-label1':'Gerekli alt ağlar:','l-s9-label2':'En büyük alt ağdaki PC:',
    'l-s9-ck1':'Alt ağlar (2 kuvveti)','l-s9-ck2':'Ödünç bitler','l-s9-ck3':'Host bitleri',
    'l-s9-ck4':'Önek uzunluğu','l-s9-ck5':'Alt ağ maskesi','l-s9-ck6':'Adres/alt ağ',
    'l-s9-ck7':'Kullanılabilir host','l-s9-ck7-err':'← çok az!','l-s9-ck8':'Teor. ağlar',
    'l-s10-h2':'10 — Hızlı referans',
    'l-s10-h3':'10 soruya genel bakış',
    'l-s10-th2':'Soru','l-s10-th3':'Formül / Yöntem',
    'l-s10-aq':'IP sınıfı','l-s10-af':'1. byte: 1–126=A, 128–191=B, 192–223=C',
    'l-s10-bq':'Gerekli alt ağlar','l-s10-bf':'SR + VW + Yedek → sonraki 2 kuvveti',
    'l-s10-cq':'Ödünç bitler','l-s10-cf':'2^x = alt ağlar → x = ?',
    'l-s10-dq':'Ger. host adresleri','l-s10-df':'En büyük odadaki PC',
    'l-s10-eq':'Host bitleri','l-s10-ef':'8 − ödünç bitler',
    'l-s10-fq':'Önek uzunluğu','l-s10-ff':'/24 + ödünç bitler',
    'l-s10-gq':'Alt ağ maskesi','l-s10-gf':'4. byte: birleri topla (128+64+32+16=240)',
    'l-s10-hq':'Adres/alt ağ','l-s10-hf':'2^(host bitleri)',
    'l-s10-iq':'Kullan. hostlar','l-s10-if':'Adres/alt ağ − 2',
    'l-s10-jq':'Teor. ağlar','l-s10-jf':'2^(ödünç bitler)',
    'l-s10-cta':'Antrenörü aç ve pratik yap!','l-s10-cta-link':'→ Antrenöre git',
    'a-hero-eyebrow':'📋 Adım adım kılavuz',
    'a-hero-h1':'Bir alt ağlama görevini nasıl çözerim?',
    'a-hero-p':'Burada tam çözüm yolunu bulursun — görevden tüm 10 cevaba kadar. Tamamen çözülmüş bir örnekle.',
    'a-section-label':'Çözüm yolu',
    'a-step1':'Görevi oku ve verileri topla','a-step2':'a) IP sınıfını belirle',
    'a-step3':'b) Gerekli alt ağları hesapla','a-step4':'c) Ödünç bitleri belirle',
    'a-step5':'d) Gerekli host adresleri','a-step6':'e) Host bitlerini hesapla',
    'a-step7':'f) Önek uzunluğunu hesapla','a-step8':'g) Alt ağ maskesini hesapla',
    'a-step9':'h & i) Alt ağ başına adresler','a-step10':'j) Teorik olarak mümkün ağlar',
    'a-example-label':'Tamamen çözülmüş örnek',
    'a-example-task':'Ağ: <code>192.168.50.0/24</code><br>Gerekli: 8 eğitim odası (her biri 12 PC) · 1 yönetim ağı (10 PC) · 1 yedek ağ (4 PC)',
    'a-example-task-label':'Görev:',
    'a-sq-a':'IP sınıfı','a-sq-b':'Gerekli alt ağlar','a-sq-c':'Ödünç bitler',
    'a-sq-d':'Ger. host adresleri','a-sq-e':'Host bitleri','a-sq-f':'Önek uzunluğu',
    'a-sq-g':'Alt ağ maskesi','a-sq-h':'Alt ağ başına adres','a-sq-i':'Kullan. hostlar','a-sq-j':'Teor. ağlar',
    'a-btn-practice':'Şimdi pratik yap →','a-btn-review':'📚 Tekrar oku',
    'how-label':'Nasıl çalışır',
    'cls-label':'IP sınıfı:', 'cls-random':'Rastgele', 'cls-a':'Sınıf A', 'cls-b':'Sınıf B', 'cls-c':'Sınıf C',
  },
  fr: {
    'l-hero-eyebrow':'📚 Référence Subnetting',
    'l-hero-h1':'Comprendre le subnetting de zéro',
    'l-hero-p':'Apprenez tout ici — des adresses IP aux nombres binaires jusqu\'au subnetting complet. Avec diagrammes, exemples et calculatrice interactive.',
    'l-nav-1':'Qu\'est-ce qu\'une adresse IP ?','l-nav-2':'Nombres binaires','l-nav-3':'Classes IP',
    'l-nav-4':'Qu\'est-ce que le subnetting ?','l-nav-5':'Masque de sous-réseau','l-nav-6':'Emprunter des bits',
    'l-nav-7':'Longueur de préfixe','l-nav-8':'Tableau de sous-réseaux','l-nav-9':'Calculatrice','l-nav-10':'Référence rapide',
    'l-s1-h2':'01 — Qu\'est-ce qu\'une adresse IP ?',
    'l-s1-intro':'Une adresse IP est comme un numéro de maison sur Internet — elle identifie de manière unique un appareil sur le réseau.',
    'l-s1-p1':'Les adresses IPv4 sont composées de <strong>4 octets</strong> (= 4 × 8 bits = 32 bits), séparés par des points :',
    'l-s1-diag-title':'Structure d\'une adresse IPv4 : 192.168.50.1',
    'l-s1-bin-label':'Chaque octet en binaire (8 bits) :',
    'l-s1-bin-note':'128+64 = <span style="color:var(--accent)">192</span> &nbsp;&nbsp; 128+32+8 = <span style="color:var(--accent)">168</span>',
    'l-s1-tip':'Un octet peut stocker des valeurs de 0 à 255 (2⁸ = 256 possibilités). C\'est pourquoi on ne voit jamais un nombre supérieur à 255 dans une adresse IP.',
    'l-s2-h2':'02 — Comprendre les nombres binaires',
    'l-s2-intro':'Les ordinateurs ne connaissent que 0 et 1. C\'est pourquoi tu dois comprendre comment fonctionnent les nombres binaires pour le subnetting.',
    'l-s2-h3a':'Valeurs de position',
    'l-s2-p1':'Chaque position a une valeur — une puissance de 2. De droite à gauche :',
    'l-s2-diag-title':'🔢 Valeurs de position d\'un octet (8 bits)',
    'l-s2-sum-note':'N\'additionner que les 1 : 128 + 64 + 16 = <span style="color:var(--green);font-weight:600">208</span>',
    'l-s2-h3b':'Table Décimal → Binaire',
    'l-s2-th1':'Décimal','l-s2-th2':'Binaire','l-s2-th3':'Explication',
    'l-s2-e1':'bit 7 uniquement','l-s2-e2':'128 + 64','l-s2-e3':'128 + 64 + 32','l-s2-e4':'128+64+32+16','l-s2-e5':'128+64+32+16+8','l-s2-e6':'tous les bits',
    'l-s3-h2':'03 — Classes IP',
    'l-s3-intro':'Les adresses IPv4 sont divisées en classes. La classe détermine la taille du réseau.',
    'l-s3-diag-title':'🏷️ Aperçu des classes IP',
    'l-s3-th1':'Classe','l-s3-th2':'Premier octet','l-s3-th3':'Plage','l-s3-th4':'Réseaux','l-s3-th5':'Hôtes/Rés.',
    'l-s3-tip':'<strong>Règle mnémotechnique :</strong> Classe C = 192–223 dans le premier octet. C\'est la classe la plus courante dans les exercices (ex. 192.168.x.x).',
    'l-s3-h3vis':'Visualisation : Quelle est la taille des classes ?',
    'l-s3-class-a':'Classe A — réseaux énormes','l-s3-hosts-a':'16 millions d\'hôtes par réseau',
    'l-s3-class-b':'Classe B — réseaux moyens','l-s3-hosts-b':'65 534 hôtes par réseau',
    'l-s3-class-c':'Classe C — petits réseaux ← on travaille ici','l-s3-hosts-c':'254 hôtes par réseau',
    'l-s4-h2':'04 — Qu\'est-ce que le subnetting ?',
    'l-s4-intro':'Le subnetting consiste à diviser un grand réseau en sous-réseaux plus petits — comme construire des murs dans une grande maison.',
    'l-s4-p1':'Imagine : tu as un immeuble de bureaux (= un réseau /24 avec 254 adresses). Tu veux un réseau séparé pour chaque département — pour que le trafic reste séparé.',
    'l-s4-diag-title':'🏢 Un réseau /24 est divisé',
    'l-s4-sub-hosts':'14 hôtes utilisables',
    'l-s4-arrow':'→ D\'un réseau /24, le subnetting crée p.ex. 16 réseaux /28 plus petits.',
    'l-s4-h3why':'Pourquoi le subnetting ?',
    'l-s4-c1h':'Ordre & structure','l-s4-c1p':'Chaque département/salle obtient son propre sous-réseau — clairement séparé et organisé.',
    'l-s4-c2h':'Sécurité','l-s4-c2p':'Les sous-réseaux peuvent être isolés — ex. le réseau bureau ne peut pas atteindre le réseau serveur.',
    'l-s4-c3h':'Moins de trafic broadcast','l-s4-c3p':'Les broadcasts restent dans le sous-réseau — soulageant ainsi tout le réseau.',
    'l-s5-h2':'05 — Le masque de sous-réseau',
    'l-s5-intro':'Le masque de sous-réseau indique quelle partie de l\'adresse IP est le <strong>réseau</strong> et quelle partie est l\'<strong>hôte</strong>.',
    'l-s5-rule':'Règle : <code>1</code> = partie réseau &nbsp;|&nbsp; <code>0</code> = partie hôte',
    'l-s5-diag1-title':'🎭 Masque de sous-réseau 255.255.255.0 (/24)',
    'l-s5-ip-label':'Adresse IP :','l-s5-mask-label':'Masque de sous-réseau :',
    'l-s5-note':'255 = tous les bits à 1 → partie réseau &nbsp;|&nbsp; 0 = tous les bits à 0 → partie hôte',
    'l-s5-diag2-title':'🎭 Masque de sous-réseau 255.255.255.240 (/28)',
    'l-s5-diag2-p':'Le 4e octet est maintenant mixte — 4 bits réseau, 4 bits hôte :',
    'l-s6-h2':'06 — Emprunter des bits',
    'l-s6-intro':'Le subnetting fonctionne ainsi : on prend des bits de la partie hôte et on les donne à la partie réseau. Cela crée plus de sous-réseaux, mais plus petits.',
    'l-s6-diag-title':'🔄 Avant /24 → Après /28 (4 bits empruntés)',
    'l-s6-before-label':'AVANT — 4e octet : tout des bits hôte',
    'l-s6-before-note':'8 bits hôte → 2⁸−2 = 254 hôtes, 1 réseau',
    'l-s6-after-label':'APRÈS — 4 bits empruntés pour les sous-réseaux',
    'l-s6-legend-s':'S = Bit sous-réseau (emprunté)','l-s6-legend-h':'H = Bit hôte (reste)',
    'l-s6-after-note':'4 bits sous-réseau → 2⁴ = <strong style="color:var(--accent)">16 sous-réseaux</strong><br>4 bits hôte → 2⁴−2 = <strong style="color:var(--green)">14 hôtes utilisables</strong> par sous-réseau',
    'l-s6-warn':'Plus de bits empruntés = plus de sous-réseaux, mais moins d\'hôtes par sous-réseau. C\'est toujours un compromis !',
    'l-s6-h3':'La formule',
    'l-s6-f1l':'Sous-réseaux','l-s6-f1r':'2^(bits empruntés)',
    'l-s6-f2l':'Hôtes par sous-réseau','l-s6-f2r':'2^(bits restants)','l-s6-f2n':'(−réseau −broadcast)',
    'l-s7-h2':'07 — Longueur de préfixe (CIDR)',
    'l-s7-intro':'La longueur de préfixe (ex. <code>/28</code>) est une notation compacte du masque de sous-réseau — elle indique combien de bits la partie réseau possède.',
    'l-s7-diag-title':'📐 /28 = 28 bits réseau',
    'l-s7-diag-note':'24 bits réseau fixes + <span style="color:var(--purple)">4 bits sous-réseau</span> = <strong style="color:var(--accent)">/28</strong> &nbsp;|&nbsp; 4 bits hôte restent',
    'l-s7-th1':'Préfixe','l-s7-th2':'Masque de s-réseau','l-s7-th3':'Bits empruntés','l-s7-th4':'Sous-réseaux','l-s7-th5':'Hôtes/S-réseau','l-s7-th6':'Taille bloc',
    'l-s8-h2':'08 — Créer un tableau de sous-réseaux',
    'l-s8-intro':'Une fois la taille de bloc connue, tu peux lister tous les sous-réseaux. Taille bloc = total adresses par sous-réseau.',
    'l-s8-p1':'Exemple : /28 → taille bloc = 16. Les sous-réseaux commencent à 0, 16, 32, 48, ...',
    'l-s8-diag-title':'📋 Tableau de sous-réseaux pour 192.168.50.0/28',
    'l-s8-th1':'N°','l-s8-th2':'ID s-réseau','l-s8-th3':'Premier hôte','l-s8-th4':'Dernier hôte','l-s8-th5':'Broadcast',
    'l-s8-h3':'Aide-mémoire pour chaque sous-réseau',
    'l-s8-c1h':'ID sous-réseau','l-s8-c1p':'= numéro du s-réseau × taille bloc (0×16=0, 1×16=16, 2×16=32 ...)',
    'l-s8-c2h':'Premier hôte','l-s8-c2p':'= ID sous-réseau + 1',
    'l-s8-c3h':'Broadcast','l-s8-c3p':'= ID sous-réseau + taille bloc − 1 (0+16−1=15)',
    'l-s8-c4h':'Dernier hôte','l-s8-c4p':'= Broadcast − 1',
    'l-s9-h2':'09 — Calculatrice de sous-réseau interactive',
    'l-s9-p':'Entre le nombre de sous-réseaux requis — la calculatrice calcule tout automatiquement.',
    'l-s9-label1':'Sous-réseaux requis :','l-s9-label2':'PC dans le plus grand sous-réseau :',
    'l-s9-ck1':'Sous-réseaux (puissance 2)','l-s9-ck2':'Bits empruntés','l-s9-ck3':'Bits hôte',
    'l-s9-ck4':'Longueur préfixe','l-s9-ck5':'Masque','l-s9-ck6':'Adresses/s-réseau',
    'l-s9-ck7':'Hôtes utilisables','l-s9-ck7-err':'← trop peu !','l-s9-ck8':'Réseaux théor.',
    'l-s10-h2':'10 — Référence rapide',
    'l-s10-h3':'Vue d\'ensemble des 10 questions',
    'l-s10-th2':'Question','l-s10-th3':'Formule / Méthode',
    'l-s10-aq':'Classe IP','l-s10-af':'1er octet : 1–126=A, 128–191=B, 192–223=C',
    'l-s10-bq':'Sous-réseaux requis','l-s10-bf':'SR + VW + Réserve → prochaine puissance de 2',
    'l-s10-cq':'Bits empruntés','l-s10-cf':'2^x = s-réseaux → x = ?',
    'l-s10-dq':'Adr. hôtes req.','l-s10-df':'PC dans la plus grande salle',
    'l-s10-eq':'Bits hôte','l-s10-ef':'8 − bits empruntés',
    'l-s10-fq':'Longueur préfixe','l-s10-ff':'/24 + bits empruntés',
    'l-s10-gq':'Masque de s-réseau','l-s10-gf':'4e octet : additionner les 1 (128+64+32+16=240)',
    'l-s10-hq':'Adresses/s-réseau','l-s10-hf':'2^(bits hôte)',
    'l-s10-iq':'Hôtes util.','l-s10-if':'Adresses/s-réseau − 2',
    'l-s10-jq':'Réseaux théor.','l-s10-jf':'2^(bits empruntés)',
    'l-s10-cta':'Ouvre l\'entraîneur et pratique !','l-s10-cta-link':'→ Vers l\'entraîneur',
    'a-hero-eyebrow':'📋 Guide étape par étape',
    'a-hero-h1':'Comment résoudre un exercice de subnetting ?',
    'a-hero-p':'Tu trouves ici le chemin de résolution complet — de l\'exercice aux 10 réponses. Avec un exemple entièrement résolu.',
    'a-section-label':'Le chemin de résolution',
    'a-step1':'Lire l\'exercice et collecter les données','a-step2':'a) Déterminer la classe IP',
    'a-step3':'b) Calculer les sous-réseaux requis','a-step4':'c) Déterminer les bits empruntés',
    'a-step5':'d) Adresses hôtes requises','a-step6':'e) Calculer les bits hôte',
    'a-step7':'f) Calculer la longueur de préfixe','a-step8':'g) Calculer le masque de sous-réseau',
    'a-step9':'h & i) Adresses par sous-réseau','a-step10':'j) Réseaux théoriquement possibles',
    'a-example-label':'Exemple entièrement résolu',
    'a-example-task':'Réseau : <code>192.168.50.0/24</code><br>Requis : 8 salles de formation (12 PC chacune) · 1 réseau admin (10 PC) · 1 réseau réserve (4 PC)',
    'a-example-task-label':'Exercice :',
    'a-sq-a':'Classe IP','a-sq-b':'Sous-réseaux requis','a-sq-c':'Bits empruntés',
    'a-sq-d':'Adr. hôtes req.','a-sq-e':'Bits hôte','a-sq-f':'Longueur préfixe',
    'a-sq-g':'Masque de s-réseau','a-sq-h':'Adresses par s-réseau','a-sq-i':'Hôtes util.','a-sq-j':'Réseaux théor.',
    'a-btn-practice':'Pratiquer maintenant →','a-btn-review':'📚 Relire la référence',
    'how-label':'Comment ça marche',
    'cls-label':'Classe IP :', 'cls-random':'Aléatoire', 'cls-a':'Classe A', 'cls-b':'Classe B', 'cls-c':'Classe C',
  },
  es: {
    'l-hero-eyebrow':'📚 Referencia Subnetting',
    'l-hero-h1':'Entiende el subnetting desde cero',
    'l-hero-p':'Aprende todo aquí — de direcciones IP a números binarios hasta subnetting completo. Con diagramas, ejemplos y calculadora interactiva.',
    'l-nav-1':'¿Qué es una dirección IP?','l-nav-2':'Números binarios','l-nav-3':'Clases IP',
    'l-nav-4':'¿Qué es el subnetting?','l-nav-5':'Máscara de subred','l-nav-6':'Préstamo de bits',
    'l-nav-7':'Longitud de prefijo','l-nav-8':'Tabla de subredes','l-nav-9':'Calculadora','l-nav-10':'Referencia rápida',
    'l-s1-h2':'01 — ¿Qué es una dirección IP?',
    'l-s1-intro':'Una dirección IP es como un número de casa en internet — identifica de forma única un dispositivo en la red.',
    'l-s1-p1':'Las direcciones IPv4 se componen de <strong>4 bytes</strong> (= 4 × 8 bits = 32 bits), separados por puntos:',
    'l-s1-diag-title':'Estructura de una dirección IPv4: 192.168.50.1',
    'l-s1-bin-label':'Cada byte en binario (8 bits):',
    'l-s1-bin-note':'128+64 = <span style="color:var(--accent)">192</span> &nbsp;&nbsp; 128+32+8 = <span style="color:var(--accent)">168</span>',
    'l-s1-tip':'Un byte puede almacenar valores de 0 a 255 (2⁸ = 256 posibilidades). Por eso nunca verás un número mayor de 255 en las direcciones IP.',
    'l-s2-h2':'02 — Entender los números binarios',
    'l-s2-intro':'Los ordenadores solo conocen el 0 y el 1. Por eso necesitas entender cómo funcionan los números binarios para el subnetting.',
    'l-s2-h3a':'Valores posicionales',
    'l-s2-p1':'Cada posición tiene un valor — una potencia de 2. De derecha a izquierda:',
    'l-s2-diag-title':'🔢 Valores posicionales de un byte (8 bits)',
    'l-s2-sum-note':'Sumar solo los 1s: 128 + 64 + 16 = <span style="color:var(--green);font-weight:600">208</span>',
    'l-s2-h3b':'Tabla Decimal → Binario',
    'l-s2-th1':'Decimal','l-s2-th2':'Binario','l-s2-th3':'Explicación',
    'l-s2-e1':'solo bit 7','l-s2-e2':'128 + 64','l-s2-e3':'128 + 64 + 32','l-s2-e4':'128+64+32+16','l-s2-e5':'128+64+32+16+8','l-s2-e6':'todos los bits',
    'l-s3-h2':'03 — Clases IP',
    'l-s3-intro':'Las direcciones IPv4 se dividen en clases. La clase determina el tamaño de la red.',
    'l-s3-diag-title':'🏷️ Resumen de clases IP',
    'l-s3-th1':'Clase','l-s3-th2':'Primer byte','l-s3-th3':'Rango','l-s3-th4':'Redes','l-s3-th5':'Hosts/Red',
    'l-s3-tip':'<strong>Regla mnemotécnica:</strong> Clase C = 192–223 en el primer byte. Es la clase más común en los ejercicios (ej. 192.168.x.x).',
    'l-s3-h3vis':'Visual: ¿Qué tan grandes son las clases?',
    'l-s3-class-a':'Clase A — redes enormes','l-s3-hosts-a':'16 millones de hosts por red',
    'l-s3-class-b':'Clase B — redes medianas','l-s3-hosts-b':'65.534 hosts por red',
    'l-s3-class-c':'Clase C — redes pequeñas ← trabajamos aquí','l-s3-hosts-c':'254 hosts por red',
    'l-s4-h2':'04 — ¿Qué es el subnetting?',
    'l-s4-intro':'El subnetting significa dividir una red grande en subredes más pequeñas — como levantar paredes en una casa grande.',
    'l-s4-p1':'Imagina: tienes un edificio de oficinas (= una red /24 con 254 direcciones). Quieres una red separada para cada departamento — para que el tráfico quede separado.',
    'l-s4-diag-title':'🏢 Una red /24 se divide',
    'l-s4-sub-hosts':'14 hosts utilizables',
    'l-s4-arrow':'→ De una red /24, el subnetting crea p.ej. 16 redes /28 más pequeñas.',
    'l-s4-h3why':'¿Por qué subnetting?',
    'l-s4-c1h':'Orden & estructura','l-s4-c1p':'Cada departamento/sala obtiene su propia subred — claramente separada y organizada.',
    'l-s4-c2h':'Seguridad','l-s4-c2p':'Las subredes pueden aislarse — ej. la red de oficinas no puede alcanzar la red de servidores.',
    'l-s4-c3h':'Menos tráfico broadcast','l-s4-c3p':'Los broadcasts permanecen en la subred — aliviando toda la red.',
    'l-s5-h2':'05 — La máscara de subred',
    'l-s5-intro':'La máscara de subred indica qué parte de la dirección IP es la <strong>red</strong> y qué parte es el <strong>host</strong>.',
    'l-s5-rule':'Regla: <code>1</code> = parte red &nbsp;|&nbsp; <code>0</code> = parte host',
    'l-s5-diag1-title':'🎭 Máscara de subred 255.255.255.0 (/24)',
    'l-s5-ip-label':'Dirección IP:','l-s5-mask-label':'Máscara de subred:',
    'l-s5-note':'255 = todos los bits en 1 → parte red &nbsp;|&nbsp; 0 = todos los bits en 0 → parte host',
    'l-s5-diag2-title':'🎭 Máscara de subred 255.255.255.240 (/28)',
    'l-s5-diag2-p':'El 4.º byte ahora es mixto — 4 bits red, 4 bits host:',
    'l-s6-h2':'06 — Préstamo de bits',
    'l-s6-intro':'El subnetting funciona así: tomas bits de la parte de host y se los das a la parte de red. Esto crea más subredes, pero más pequeñas.',
    'l-s6-diag-title':'🔄 Antes /24 → Después /28 (4 bits prestados)',
    'l-s6-before-label':'ANTES — 4.º byte: todos bits de host',
    'l-s6-before-note':'8 bits host → 2⁸−2 = 254 hosts, 1 red',
    'l-s6-after-label':'DESPUÉS — 4 bits prestados para subredes',
    'l-s6-legend-s':'S = Bit subred (prestado)','l-s6-legend-h':'H = Bit host (queda)',
    'l-s6-after-note':'4 bits subred → 2⁴ = <strong style="color:var(--accent)">16 subredes</strong><br>4 bits host → 2⁴−2 = <strong style="color:var(--green)">14 hosts utilizables</strong> por subred',
    'l-s6-warn':'Más bits prestados = más subredes, pero menos hosts por subred. ¡Siempre es un compromiso!',
    'l-s6-h3':'La fórmula',
    'l-s6-f1l':'Subredes','l-s6-f1r':'2^(bits prestados)',
    'l-s6-f2l':'Hosts por subred','l-s6-f2r':'2^(bits restantes)','l-s6-f2n':'(−red −broadcast)',
    'l-s7-h2':'07 — Longitud de prefijo (CIDR)',
    'l-s7-intro':'La longitud de prefijo (ej. <code>/28</code>) es una notación compacta de la máscara de subred — indica cuántos bits tiene la parte de red.',
    'l-s7-diag-title':'📐 /28 = 28 bits de red',
    'l-s7-diag-note':'24 bits de red fijos + <span style="color:var(--purple)">4 bits de subred</span> = <strong style="color:var(--accent)">/28</strong> &nbsp;|&nbsp; 4 bits de host quedan',
    'l-s7-th1':'Prefijo','l-s7-th2':'Máscara de subred','l-s7-th3':'Bits prestados','l-s7-th4':'Subredes','l-s7-th5':'Hosts/Subred','l-s7-th6':'Tamaño bloque',
    'l-s8-h2':'08 — Crear una tabla de subredes',
    'l-s8-intro':'Una vez que conoces el tamaño de bloque, puedes listar todas las subredes. Tamaño bloque = total de direcciones por subred.',
    'l-s8-p1':'Ejemplo: /28 → tamaño bloque = 16. Las subredes comienzan en 0, 16, 32, 48, ...',
    'l-s8-diag-title':'📋 Tabla de subredes para 192.168.50.0/28',
    'l-s8-th1':'Nº','l-s8-th2':'ID subred','l-s8-th3':'Primer host','l-s8-th4':'Último host','l-s8-th5':'Broadcast',
    'l-s8-h3':'Regla nemotécnica para cada subred',
    'l-s8-c1h':'ID de subred','l-s8-c1p':'= número de subred × tamaño bloque (0×16=0, 1×16=16, 2×16=32 ...)',
    'l-s8-c2h':'Primer host','l-s8-c2p':'= ID subred + 1',
    'l-s8-c3h':'Broadcast','l-s8-c3p':'= ID subred + tamaño bloque − 1 (0+16−1=15)',
    'l-s8-c4h':'Último host','l-s8-c4p':'= Broadcast − 1',
    'l-s9-h2':'09 — Calculadora de subred interactiva',
    'l-s9-p':'Ingresa el número de subredes requeridas — la calculadora calcula todo automáticamente.',
    'l-s9-label1':'Subredes requeridas:','l-s9-label2':'PCs en la subred más grande:',
    'l-s9-ck1':'Subredes (potencia de 2)','l-s9-ck2':'Bits prestados','l-s9-ck3':'Bits de host',
    'l-s9-ck4':'Longitud prefijo','l-s9-ck5':'Máscara de subred','l-s9-ck6':'Direcciones/subred',
    'l-s9-ck7':'Hosts utilizables','l-s9-ck7-err':'← ¡muy pocos!','l-s9-ck8':'Redes teór.',
    'l-s10-h2':'10 — Referencia rápida',
    'l-s10-h3':'Resumen de las 10 preguntas',
    'l-s10-th2':'Pregunta','l-s10-th3':'Fórmula / Método',
    'l-s10-aq':'Clase IP','l-s10-af':'1.er byte: 1–126=A, 128–191=B, 192–223=C',
    'l-s10-bq':'Subredes requeridas','l-s10-bf':'SR + VW + Reserva → próxima potencia de 2',
    'l-s10-cq':'Bits prestados','l-s10-cf':'2^x = subredes → x = ?',
    'l-s10-dq':'Dir. host req.','l-s10-df':'PCs en la sala más grande',
    'l-s10-eq':'Bits de host','l-s10-ef':'8 − bits prestados',
    'l-s10-fq':'Longitud prefijo','l-s10-ff':'/24 + bits prestados',
    'l-s10-gq':'Máscara de subred','l-s10-gf':'4.º byte: sumar unos (128+64+32+16=240)',
    'l-s10-hq':'Direcciones/subred','l-s10-hf':'2^(bits de host)',
    'l-s10-iq':'Hosts util.','l-s10-if':'Direcciones/subred − 2',
    'l-s10-jq':'Redes teór.','l-s10-jf':'2^(bits prestados)',
    'l-s10-cta':'¡Abre el entrenador y practica!','l-s10-cta-link':'→ Al entrenador',
    'a-hero-eyebrow':'📋 Guía paso a paso',
    'a-hero-h1':'¿Cómo resuelvo una tarea de subnetting?',
    'a-hero-p':'Aquí encuentras el camino de solución completo — desde la tarea hasta las 10 respuestas. Con un ejemplo completamente resuelto.',
    'a-section-label':'El camino de solución',
    'a-step1':'Leer la tarea y recopilar datos','a-step2':'a) Determinar la clase IP',
    'a-step3':'b) Calcular las subredes requeridas','a-step4':'c) Determinar los bits prestados',
    'a-step5':'d) Direcciones de host requeridas','a-step6':'e) Calcular bits de host',
    'a-step7':'f) Calcular longitud de prefijo','a-step8':'g) Calcular máscara de subred',
    'a-step9':'h & i) Direcciones por subred','a-step10':'j) Redes teóricamente posibles',
    'a-example-label':'Ejemplo completamente resuelto',
    'a-example-task':'Red: <code>192.168.50.0/24</code><br>Requerido: 8 aulas (12 PCs cada una) · 1 red de administración (10 PCs) · 1 red de reserva (4 PCs)',
    'a-example-task-label':'Tarea:',
    'a-sq-a':'Clase IP','a-sq-b':'Subredes requeridas','a-sq-c':'Bits prestados',
    'a-sq-d':'Dir. host req.','a-sq-e':'Bits de host','a-sq-f':'Longitud prefijo',
    'a-sq-g':'Máscara de subred','a-sq-h':'Direcciones por subred','a-sq-i':'Hosts util.','a-sq-j':'Redes teór.',
    'a-btn-practice':'Practicar ahora →','a-btn-review':'📚 Leer la referencia de nuevo',
    'how-label':'Cómo funciona',
    'cls-label':'Clase IP:', 'cls-random':'Aleatorio', 'cls-a':'Clase A', 'cls-b':'Clase B', 'cls-c':'Clase C',
  },
};

/* ── Apply data-i18n / data-i18n-html attributes ── */
function applyI18n() {
  const trans = PAGE_TRANS[currentLang] || PAGE_TRANS['de'];
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const v = trans[el.getAttribute('data-i18n')];
    if (v !== undefined) el.textContent = v;
  });
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const v = trans[el.getAttribute('data-i18n-html')];
    if (v !== undefined) el.innerHTML = v;
  });
}

/* ── Active language (persisted) ── */
let currentLang = localStorage.getItem('sm-lang') || 'de';

function getLang() {
  return LANGS[currentLang] || LANGS['de'];
}

function setLang(lang, callback) {
  currentLang = lang;
  localStorage.setItem('sm-lang', lang);
  /* FIX: also update html element attributes */
  const L = LANGS[lang] || LANGS['de'];
  document.documentElement.lang = lang;
  document.body.setAttribute('dir', L.dir);
  if (callback) callback();
}
