/* ════════════════════════════════════════
   SubnetMaster – Language Translations v1.1
   FIX: setLang now updates html lang attribute + dir
   ════════════════════════════════════════ */

const LANGS = {
  de: {
    dir:'ltr',
    nav:{ trainer:'Trainer', lernen:'Lexikon', anleitung:'Anleitung' },
    eyebrow:'Subnetting Trainer',
    title:'Subnetze rechnen', span:'ohne Fehler.',
    sub:'Übe Subnetting mit zufällig generierten Aufgaben. Bei jedem Fehler siehst du eine Schritt-für-Schritt Erklärung.',
    ctaText:'Aufgabe starten',
    slDone:'Aufgaben gelöst', slCorrect:'Richtige Antworten', slPct:'Trefferquote', slStreak:'Aktuelle Serie',
    lblTask:'Aktuelle Aufgabe', lblNetwork:'Netzwerk', lblNeeded:'Benötigt',
    lblQuestions:'Fragen beantworten',
    btnNew:'Neue Aufgabe', btnCheck:'Antworten prüfen',
    maskLabel:'Subnetzmaske', hostsLabel:'Verfügbare Hosts',
    srLabel:(sr,pc) => `${sr} Schulungsräume (je ${pc} PCs)`,
    vwLabel:(vw)    => `1 Verwaltungsnetz (${vw} PCs)`,
    rsLabel:(rs)    => `1 Reservenetz (${rs} PCs)`,
    solHeader:'Alle richtigen Antworten',
    scorePerfect:(t)   => `🎉 Perfekt! Alle ${t}/${t} richtig!`,
    scoreGood:(c,t)    => `👍 Gut! ${c}/${t} richtig — schau dir die Erklärungen an.`,
    scoreRetry:(c,t)   => `💪 ${c}/${t} richtig — lies die Erklärungen und versuch es nochmal!`,
    badgeOk:'✓ Richtig', badgeErr:'✗ Falsch',
    explainTitle:(ans) => `Richtige Antwort: ${ans} — so geht es:`,
    qTexts:[
      'Zu welcher Klasse gehört die IP-Adresse?',
      'Anzahl der benötigten Subnetze (als 2er-Potenz)',
      'Anzahl der entliehenen Subnetzbits (4. Byte)',
      'Anzahl der erforderlichen Hostadressen',
      'Erforderliche Anzahl der Hostbits',
      'Passende Präfixlänge (/-Notation)',
      'Subnetzmaske',
      'Gesamtzahl der Adressen je Subnetz',
      'Tatsächlich verwendbare Hostadressen pro Subnetz',
      'Wie viele Netze sind theoretisch möglich?'
    ],
    qPh:['z.B. C','z.B. 16','z.B. 4','z.B. 12','z.B. 4','z.B. /28','z.B. 255.255.255.240','z.B. 16','z.B. 14','z.B. 16'],
    solKeys:['Klasse','Subnetze','Subnetzbits','Erf. Hosts','Hostbits','Präfix','Subnetzmaske','Adressen/Subnetz','Nutzb. Hosts','Theor. Netze'],
    how:[
      {num:'01', title:'Aufgabe lesen',     text:'Lies das Netz und die benötigten Subnetze.'},
      {num:'02', title:'Antworten eingeben',text:'Füll alle 10 Felder aus. Enter springt zur nächsten Frage.'},
      {num:'03', title:'Prüfen & lernen',   text:'Bei einem Fehler erscheint eine Schritt-für-Schritt Erklärung.'},
      {num:'04', title:'Serie aufbauen',    text:'Lös Aufgaben fehlerfrei und bau deine Serie aus.'}
    ],
    footerText:'SubnetMaster — Klasse 1aAPC',
  },
  en: {
    dir:'ltr',
    nav:{ trainer:'Trainer', lernen:'Reference', anleitung:'Guide' },
    eyebrow:'Subnetting Trainer',
    title:'Calculate subnets', span:'without mistakes.',
    sub:'Practice subnetting with randomly generated tasks. Every mistake shows you a step-by-step explanation.',
    ctaText:'Start exercise',
    slDone:'Tasks solved', slCorrect:'Correct answers', slPct:'Accuracy', slStreak:'Current streak',
    lblTask:'Current task', lblNetwork:'Network', lblNeeded:'Required',
    lblQuestions:'Answer the questions',
    btnNew:'New task', btnCheck:'Check answers',
    maskLabel:'Subnet mask', hostsLabel:'Available hosts',
    srLabel:(sr,pc) => `${sr} training rooms (${pc} PCs each)`,
    vwLabel:(vw)    => `1 admin network (${vw} PCs)`,
    rsLabel:(rs)    => `1 reserve network (${rs} PCs)`,
    solHeader:'All correct answers',
    scorePerfect:(t)   => `🎉 Perfect! All ${t}/${t} correct!`,
    scoreGood:(c,t)    => `👍 Good! ${c}/${t} correct — check the explanations.`,
    scoreRetry:(c,t)   => `💪 ${c}/${t} correct — read the explanations and try again!`,
    badgeOk:'✓ Correct', badgeErr:'✗ Wrong',
    explainTitle:(ans) => `Correct answer: ${ans} — here's how:`,
    qTexts:[
      'Which class does the IP address belong to?',
      'Number of required subnets (power of 2)',
      'Borrowed subnet bits (4th byte)',
      'Number of required host addresses',
      'Required number of host bits',
      'Correct prefix length (slash notation)',
      'Subnet mask',
      'Total addresses per subnet',
      'Usable host addresses per subnet',
      'How many networks are theoretically possible?'
    ],
    qPh:['e.g. C','e.g. 16','e.g. 4','e.g. 12','e.g. 4','e.g. /28','e.g. 255.255.255.240','e.g. 16','e.g. 14','e.g. 16'],
    solKeys:['Class','Subnets','Subnet bits','Req. hosts','Host bits','Prefix','Subnet mask','Addr/subnet','Usable hosts','Theor. nets'],
    how:[
      {num:'01', title:'Read the task',    text:'Look at the network and the required subnets above.'},
      {num:'02', title:'Enter answers',    text:'Fill in all 10 fields. Press Enter to jump to next.'},
      {num:'03', title:'Check & learn',    text:'A wrong answer shows a step-by-step explanation.'},
      {num:'04', title:'Build a streak',   text:'Solve tasks perfectly and grow your streak counter.'}
    ],
    footerText:'SubnetMaster — Class 1aAPC',
  },
  ar: {
    dir:'rtl',
    nav:{ trainer:'المدرب', lernen:'القاموس', anleitung:'الدليل' },
    eyebrow:'مدرب تقسيم الشبكات',
    title:'احسب الشبكات الفرعية', span:'بدون أخطاء.',
    sub:'تدرب على تقسيم الشبكات مع تمارين عشوائية. عند كل خطأ ستظهر لك شرح خطوة بخطوة.',
    ctaText:'ابدأ التمرين',
    slDone:'تمارين محلولة', slCorrect:'إجابات صحيحة', slPct:'نسبة الدقة', slStreak:'السلسلة الحالية',
    lblTask:'التمرين الحالي', lblNetwork:'الشبكة', lblNeeded:'المطلوب',
    lblQuestions:'أجب على الأسئلة',
    btnNew:'تمرين جديد', btnCheck:'تحقق من الإجابات',
    maskLabel:'قناع الشبكة', hostsLabel:'المضيفون المتاحون',
    srLabel:(sr,pc) => `${sr} غرفة تدريب (${pc} جهاز لكل غرفة)`,
    vwLabel:(vw)    => `1 شبكة إدارة (${vw} أجهزة)`,
    rsLabel:(rs)    => `1 شبكة احتياطية (${rs} أجهزة)`,
    solHeader:'جميع الإجابات الصحيحة',
    scorePerfect:(t)   => `🎉 ممتاز! جميع ${t}/${t} صحيحة! مبروك!`,
    scoreGood:(c,t)    => `👍 أحسنت! ${c}/${t} صحيحة — راجع الشرح.`,
    scoreRetry:(c,t)   => `💪 ${c}/${t} صحيحة — اقرأ الشرح وحاول مرة أخرى!`,
    badgeOk:'✓ صحيح', badgeErr:'✗ خطأ',
    explainTitle:(ans) => `الإجابة الصحيحة: ${ans} — إليك الطريقة:`,
    qTexts:[
      'إلى أي فئة تنتمي عنوان IP؟',
      'عدد الشبكات الفرعية المطلوبة (قوة للعدد 2)',
      'عدد البتات المستعارة (البايت الرابع)',
      'عدد عناوين المضيفين المطلوبة',
      'عدد بتات المضيف المطلوبة',
      'طول البادئة المناسب (صيغة الشرطة)',
      'قناع الشبكة الفرعية',
      'إجمالي عدد العناوين لكل شبكة فرعية',
      'عناوين المضيفين القابلة للاستخدام لكل شبكة',
      'كم شبكة فرعية ممكنة نظرياً؟'
    ],
    qPh:['مثال: C','مثال: 16','مثال: 4','مثال: 12','مثال: 4','مثال: /28','مثال: 255.255.255.240','مثال: 16','مثال: 14','مثال: 16'],
    solKeys:['الفئة','الشبكات','بتات الشبكة','المضيفون المطلوبون','بتات المضيف','البادئة','قناع الشبكة','عناوين/شبكة','مضيفون صالحون','شبكات نظرية'],
    how:[
      {num:'٠١', title:'اقرأ التمرين',  text:'انظر إلى الشبكة والشبكات الفرعية المطلوبة.'},
      {num:'٠٢', title:'أدخل الإجابات',text:'أكمل الحقول العشرة. Enter للانتقال للتالي.'},
      {num:'٠٣', title:'تحقق وتعلم',   text:'عند الخطأ يظهر شرح خطوة بخطوة.'},
      {num:'٠٤', title:'ابنِ سلسلتك',  text:'حل التمارين بشكل صحيح وازدد سلسلتك.'}
    ],
    footerText:'SubnetMaster — الصف 1aAPC',
  },
  tr: {
    dir:'ltr',
    nav:{ trainer:'Antrenör', lernen:'Sözlük', anleitung:'Kılavuz' },
    eyebrow:'Alt Ağ Eğitmeni',
    title:'Alt ağları hesapla', span:'hatasız.',
    sub:'Rastgele görevlerle alt ağ hesaplamasını pratik yap. Her hatada adım adım açıklama görürsün.',
    ctaText:'Göreve başla',
    slDone:'Çözülen görevler', slCorrect:'Doğru cevaplar', slPct:'İsabet oranı', slStreak:'Mevcut seri',
    lblTask:'Mevcut görev', lblNetwork:'Ağ', lblNeeded:'Gerekli',
    lblQuestions:'Soruları cevapla',
    btnNew:'Yeni görev', btnCheck:'Cevapları kontrol et',
    maskLabel:'Alt ağ maskesi', hostsLabel:'Kullanılabilir hostlar',
    srLabel:(sr,pc) => `${sr} eğitim odası (her biri ${pc} PC)`,
    vwLabel:(vw)    => `1 yönetim ağı (${vw} PC)`,
    rsLabel:(rs)    => `1 yedek ağ (${rs} PC)`,
    solHeader:'Tüm doğru cevaplar',
    scorePerfect:(t)   => `🎉 Mükemmel! ${t}/${t} doğru!`,
    scoreGood:(c,t)    => `👍 Güzel! ${c}/${t} doğru — açıklamalara bak.`,
    scoreRetry:(c,t)   => `💪 ${c}/${t} doğru — açıklamaları oku ve tekrar dene!`,
    badgeOk:'✓ Doğru', badgeErr:'✗ Yanlış',
    explainTitle:(ans) => `Doğru cevap: ${ans} — adımlar:`,
    qTexts:[
      'IP adresi hangi sınıfa ait?',
      'Gerekli alt ağ sayısı (2\'nin kuvveti)',
      'Ödünç alınan bit sayısı (4. bayt)',
      'Gerekli host adresi sayısı',
      'Gerekli host bit sayısı',
      'Önek uzunluğu (/ notasyonu)',
      'Alt ağ maskesi',
      'Alt ağ başına toplam adres',
      'Kullanılabilir host adresleri',
      'Teorik ağ sayısı'
    ],
    qPh:['örn. C','örn. 16','örn. 4','örn. 12','örn. 4','örn. /28','örn. 255.255.255.240','örn. 16','örn. 14','örn. 16'],
    solKeys:['Sınıf','Alt ağlar','Subnet bitleri','Ger. hostlar','Host bitleri','Önek','Alt ağ maskesi','Adres/ağ','Kullan. hostlar','Teor. ağlar'],
    how:[
      {num:'01', title:'Görevi oku',       text:'Ağı ve gereken alt ağları incele.'},
      {num:'02', title:'Cevapları gir',    text:'10 alanı doldur. Enter ile sonrakine geç.'},
      {num:'03', title:'Kontrol et & öğren',text:'Yanlış cevapta açıklama çıkar.'},
      {num:'04', title:'Seri oluştur',     text:'Görevleri hatasız çöz.'}
    ],
    footerText:'SubnetMaster — Sınıf 1aAPC',
  },
  fr: {
    dir:'ltr',
    nav:{ trainer:'Entraîneur', lernen:'Référence', anleitung:'Guide' },
    eyebrow:'Entraîneur Subnetting',
    title:'Calculer les sous-réseaux', span:'sans erreur.',
    sub:'Entraîne-toi avec des exercices aléatoires. Chaque erreur affiche une explication étape par étape.',
    ctaText:'Commencer',
    slDone:'Exercices résolus', slCorrect:'Réponses correctes', slPct:'Précision', slStreak:'Série',
    lblTask:'Exercice actuel', lblNetwork:'Réseau', lblNeeded:'Requis',
    lblQuestions:'Répondre aux questions',
    btnNew:'Nouvel exercice', btnCheck:'Vérifier',
    maskLabel:'Masque', hostsLabel:'Hôtes disponibles',
    srLabel:(sr,pc) => `${sr} salles (${pc} PC chacune)`,
    vwLabel:(vw)    => `1 réseau admin (${vw} PC)`,
    rsLabel:(rs)    => `1 réseau réserve (${rs} PC)`,
    solHeader:'Toutes les bonnes réponses',
    scorePerfect:(t)   => `🎉 Parfait ! ${t}/${t} !`,
    scoreGood:(c,t)    => `👍 Bien ! ${c}/${t} — regarde les explications.`,
    scoreRetry:(c,t)   => `💪 ${c}/${t} — lis les explications et réessaie !`,
    badgeOk:'✓ Correct', badgeErr:'✗ Faux',
    explainTitle:(ans) => `Bonne réponse : ${ans}`,
    qTexts:[
      'Classe de l\'adresse IP ?',
      'Nombre de sous-réseaux requis (puissance de 2)',
      'Bits empruntés (4e octet)',
      'Adresses hôtes requises',
      'Bits hôtes requis',
      'Longueur de préfixe',
      'Masque de sous-réseau',
      'Total d\'adresses par sous-réseau',
      'Adresses hôtes utilisables',
      'Réseaux théoriquement possibles ?'
    ],
    qPh:['ex. C','ex. 16','ex. 4','ex. 12','ex. 4','ex. /28','ex. 255.255.255.240','ex. 16','ex. 14','ex. 16'],
    solKeys:['Classe','Sous-réseaux','Bits','Hôtes req.','Bits hôtes','Préfixe','Masque','Adr./s-réseau','Hôtes util.','Réseaux'],
    how:[
      {num:'01', title:'Lire',     text:'Observe le réseau et les sous-réseaux.'},
      {num:'02', title:'Saisir',   text:'Remplis les 10 champs.'},
      {num:'03', title:'Vérifier', text:'Une erreur → explication.'},
      {num:'04', title:'Série',    text:'Résous sans erreur.'}
    ],
    footerText:'SubnetMaster — Classe 1aAPC',
  },
  es: {
    dir:'ltr',
    nav:{ trainer:'Entrenador', lernen:'Referencia', anleitung:'Guía' },
    eyebrow:'Entrenador Subnetting',
    title:'Calcular subredes', span:'sin errores.',
    sub:'Practica subnetting con ejercicios aleatorios. Cada error muestra una explicación paso a paso.',
    ctaText:'Iniciar ejercicio',
    slDone:'Ejercicios resueltos', slCorrect:'Respuestas correctas', slPct:'Precisión', slStreak:'Racha',
    lblTask:'Ejercicio actual', lblNetwork:'Red', lblNeeded:'Requerido',
    lblQuestions:'Responder preguntas',
    btnNew:'Nuevo ejercicio', btnCheck:'Comprobar respuestas',
    maskLabel:'Máscara de subred', hostsLabel:'Hosts disponibles',
    srLabel:(sr,pc) => `${sr} aulas (${pc} PC cada una)`,
    vwLabel:(vw)    => `1 red de administración (${vw} PC)`,
    rsLabel:(rs)    => `1 red de reserva (${rs} PC)`,
    solHeader:'Todas las respuestas correctas',
    scorePerfect:(t)   => `🎉 ¡Perfecto! ¡${t}/${t}!`,
    scoreGood:(c,t)    => `👍 ¡Bien! ${c}/${t} — mira las explicaciones.`,
    scoreRetry:(c,t)   => `💪 ${c}/${t} — lee y vuelve a intentarlo.`,
    badgeOk:'✓ Correcto', badgeErr:'✗ Incorrecto',
    explainTitle:(ans) => `Respuesta: ${ans}`,
    qTexts:[
      '¿Clase de la dirección IP?',
      'Subredes requeridas (potencia de 2)',
      'Bits prestados (4.º octeto)',
      'Direcciones de host requeridas',
      'Bits de host requeridos',
      'Longitud de prefijo',
      'Máscara de subred',
      'Total de direcciones por subred',
      'Hosts utilizables por subred',
      '¿Redes teóricamente posibles?'
    ],
    qPh:['p.ej. C','p.ej. 16','p.ej. 4','p.ej. 12','p.ej. 4','p.ej. /28','p.ej. 255.255.255.240','p.ej. 16','p.ej. 14','p.ej. 16'],
    solKeys:['Clase','Subredes','Bits','Hosts req.','Bits host','Prefijo','Máscara','Dir./subred','Hosts util.','Redes teór.'],
    how:[
      {num:'01', title:'Leer',     text:'Observa la red y las subredes.'},
      {num:'02', title:'Ingresar', text:'Rellena los 10 campos.'},
      {num:'03', title:'Verificar',text:'Un error → explicación.'},
      {num:'04', title:'Racha',    text:'Resuelve sin errores.'}
    ],
    footerText:'SubnetMaster — Clase 1aAPC',
  },
};

/* ── Active language (persisted) ── */
let currentLang = localStorage.getItem('sm-lang') || 'de';

function getLang() {
  return LANGS[currentLang] || LANGS['de'];
}

function setLang(lang, callback) {
  currentLang = lang;
  localStorage.setItem('sm-lang', lang);
  /* FIX: also update html element attributes */
  const L = LANGS[lang] || LANGS['de'];
  document.documentElement.lang = lang;
  document.body.setAttribute('dir', L.dir);
  if (callback) callback();
}
